infilename: ~/Downloads/CrossSec_dataDriven_Ds_FDen_pt2_12_conservative_TEST.root
extrap:
    FONLLfilename: ../models/fonll/feeddown/DmesonLcPredictions_502TeV_y05_FFppbar_BRpythia8_SepContr_PDG2020.root
    hist:
        cent: hDsPhipitoKkpifromBpred_central_corr
        min: hDsPhipitoKkpifromBpred_min_corr
        max: hDsPhipitoKkpifromBpred_max_corr
    ptlims: [12, 16, 24, 36]

outfilename: 'NonPromptDs_ppreference_5TeV_noyshift_pt_2_4_6_8_12_FONLLextrap_pt_16_24_36_ML.root'