input: # files to use
    prompt: /home/alidock/DmesonAnalysis/ML/parquet_file/Prompt_STE__pT_1_50.parquet.gzip
    FD: /home/alidock/DmesonAnalysis/ML/parquet_file/FD_STE__pT_1_50.parquet.gzip
    Bkg: /home/alidock/DmesonAnalysis/ML/parquet_file/Bkg_STE__pT_1_50.parquet.gzip

output:
    leg_labels: ['Background', 'Prompt D$_s$', 'Feed-down D$_s$'] # legend labels
    out_labels: ['Bkg', 'Prompt', 'FD'] # output labels
    dir: '/home/alidock/DmesonAnalysis/ML/AnalysisDs_STE/MLoutput' # output dir

pt_ranges: # ranges in pt to split the data in the ml training and testing
    min: [1, 2, 4, 6, 12] # list
    max: [2, 4, 6, 12, 50] # list

filtering:
    bkg_mass: inv_mass < 1.82 or 1.92 < inv_mass < 2.00 # pandas query to select bkg candidates

ml: # not used in first approach
    training_columns: [d_len, d_len_xy, norm_dl_xy, cos_p, cos_p_xy, imp_par_xy, sig_vert, #max_norm_d0d0exp, 
                       #nsigComb_Pi_0, nsigComb_K_0, nsigComb_Pi_1, nsigComb_K_1, nsigComb_Pi_2, nsigComb_K_2]#
                        ] # list of training variables
    plotting_columns: [inv_mass, pt_cand, d_len, d_len_xy, norm_dl_xy, cos_p, cos_p_xy, imp_par_xy, sig_vert, 
                       max_norm_d0d0exp, nsigComb_Pi_0, nsigComb_K_0, nsigComb_Pi_1, nsigComb_K_1, nsigComb_Pi_2, 
                       nsigComb_K_2] # list of variables to plot
    hyper_par: {'max_depth':3, 'learning_rate':0.12, 'n_estimators':250, 'min_child_weight':5, 'colsample':0.9}