njobs: 4

cfgtrainfiles: [
        # "/home/dbattistini/DmesonAnalysis/ML/config_Training_LctopK0s_default_2_4.yml",
        # "/home/dbattistini/DmesonAnalysis/ML/config_Training_LctopK0s_default_4_6.yml",
        # "/home/dbattistini/DmesonAnalysis/ML/config_Training_LctopK0s_default_6_8.yml",
        # "/home/dbattistini/DmesonAnalysis/ML/config_Training_LctopK0s_default_8_12.yml",
        # "/home/dbattistini/DmesonAnalysis/ML/config_Training_LctopK0s_oldconf_2_4.yml",
        # "/home/dbattistini/DmesonAnalysis/ML/config_Training_LctopK0s_oldconf_4_6.yml",
        # "/home/dbattistini/DmesonAnalysis/ML/config_Training_LctopK0s_oldconf_6_8.yml",
        # "/home/dbattistini/DmesonAnalysis/ML/config_Training_LctopK0s_oldconf_8_12.yml",
        # "/home/dbattistini/DmesonAnalysis/ML/config_Training_LctopK0s_signd0_2_4.yml",
        # "/home/dbattistini/DmesonAnalysis/ML/config_Training_LctopK0s_signd0_4_6.yml",
        # "/home/dbattistini/DmesonAnalysis/ML/config_Training_LctopK0s_signd0_6_8.yml",
        # "/home/dbattistini/DmesonAnalysis/ML/config_Training_LctopK0s_signd0_8_12.yml",
        # "/home/dbattistini/DmesonAnalysis/ML/config_Training_LctopK0s_cospV0_2_4.yml",
        # "/home/dbattistini/DmesonAnalysis/ML/config_Training_LctopK0s_cospV0_4_6.yml",
        # "/home/dbattistini/DmesonAnalysis/ML/config_Training_LctopK0s_cospV0_6_8.yml",
        # "/home/dbattistini/DmesonAnalysis/ML/config_Training_LctopK0s_cospV0_8_12.yml",
        # "/home/dbattistini/DmesonAnalysis/ML/config_Training_LctopK0s_nsigsignd0_2_4.yml",
        # "/home/dbattistini/DmesonAnalysis/ML/config_Training_LctopK0s_nsigsignd0_4_6.yml",
        # "/home/dbattistini/DmesonAnalysis/ML/config_Training_LctopK0s_nsigsignd0_6_8.yml",
        # "/home/dbattistini/DmesonAnalysis/ML/config_Training_LctopK0s_nsigsignd0_8_12.yml",
        "/home/dbattistini/DmesonAnalysis/ML/config_Training_LctopK0s_nsigcospV0_2_4.yml",
        "/home/dbattistini/DmesonAnalysis/ML/config_Training_LctopK0s_nsigcospV0_4_6.yml",
        "/home/dbattistini/DmesonAnalysis/ML/config_Training_LctopK0s_nsigcospV0_6_8.yml",
        "/home/dbattistini/DmesonAnalysis/ML/config_Training_LctopK0s_nsigcospV0_8_12.yml",
    ]

cfgapplyfiles: [
        # "/home/dbattistini/DmesonAnalysis/ML/config_Application_LctopK0s_default_2_4.yml",
        # "/home/dbattistini/DmesonAnalysis/ML/config_Application_LctopK0s_default_4_6.yml",
        # "/home/dbattistini/DmesonAnalysis/ML/config_Application_LctopK0s_default_6_8.yml",
        # "/home/dbattistini/DmesonAnalysis/ML/config_Application_LctopK0s_default_8_12.yml",
        # "/home/dbattistini/DmesonAnalysis/ML/config_Application_LctopK0s_oldconf_2_4.yml",
        # "/home/dbattistini/DmesonAnalysis/ML/config_Application_LctopK0s_oldconf_4_6.yml",
        # "/home/dbattistini/DmesonAnalysis/ML/config_Application_LctopK0s_oldconf_6_8.yml",
        # "/home/dbattistini/DmesonAnalysis/ML/config_Application_LctopK0s_oldconf_8_12.yml",
        # "/home/dbattistini/DmesonAnalysis/ML/config_Application_LctopK0s_signd0_2_4.yml",
        # "/home/dbattistini/DmesonAnalysis/ML/config_Application_LctopK0s_signd0_4_6.yml",
        # "/home/dbattistini/DmesonAnalysis/ML/config_Application_LctopK0s_signd0_6_8.yml",
        # "/home/dbattistini/DmesonAnalysis/ML/config_Application_LctopK0s_signd0_8_12.yml",
        # "/home/dbattistini/DmesonAnalysis/ML/config_Application_LctopK0s_cospV0_2_4.yml",
        # "/home/dbattistini/DmesonAnalysis/ML/config_Application_LctopK0s_cospV0_4_6.yml",
        # "/home/dbattistini/DmesonAnalysis/ML/config_Application_LctopK0s_cospV0_6_8.yml",
        # "/home/dbattistini/DmesonAnalysis/ML/config_Application_LctopK0s_cospV0_8_12.yml",
        # "/home/dbattistini/DmesonAnalysis/ML/config_Application_LctopK0s_nsigsignd0_2_4.yml",
        # "/home/dbattistini/DmesonAnalysis/ML/config_Application_LctopK0s_nsigsignd0_4_6.yml",
        # "/home/dbattistini/DmesonAnalysis/ML/config_Application_LctopK0s_nsigsignd0_6_8.yml",
        # "/home/dbattistini/DmesonAnalysis/ML/config_Application_LctopK0s_nsigsignd0_8_12.yml",
        "/home/dbattistini/DmesonAnalysis/ML/config_Application_LctopK0s_nsigcospV0_2_4.yml",
        "/home/dbattistini/DmesonAnalysis/ML/config_Application_LctopK0s_nsigcospV0_4_6.yml",
        "/home/dbattistini/DmesonAnalysis/ML/config_Application_LctopK0s_nsigcospV0_6_8.yml",
        "/home/dbattistini/DmesonAnalysis/ML/config_Application_LctopK0s_nsigcospV0_8_12.yml",
    ]
