# Description: Configuration file for the flow analysis of D mesons, ordered as follows:
# 1. Global info
# 2. Fit options
# 3. BDT cut
# 4. Optional settings
# 5. Used for computing pT weights
# global info (do not change)
axes: {mass: 0,
       pt: 1,
       cent: 2,
       sp: 5,
       deltaphi: 4,
       phi: 3,
       bdt_bkg: 6,
       bdt_sig: 7}

# cut variation general configurables
centrality: 'k3050' # centrality class
res_file: '/media/wuct/wulby/ALICE/AnRes/resolution/output_reso/resosp3050l_PASS4_full_PbPb_Reso.root' 
out_dir: '/home/wuct/ALICE/local/Results/test'
suffix: 'fd'
anresdir: [
  /home/wuct/ALICE/local/Results/pre/pre_k3050/AnRes/AnalysisResults_pt_5_10.root,
  /home/wuct/ALICE/local/Results/pre/pre_k3050/AnRes/AnalysisResults_pt_10_15.root,
  /home/wuct/ALICE/local/Results/pre/pre_k3050/AnRes/AnalysisResults_pt_15_20.root,
  /home/wuct/ALICE/local/Results/pre/pre_k3050/AnRes/AnalysisResults_pt_20_25.root,
  /home/wuct/ALICE/local/Results/pre/pre_k3050/AnRes/AnalysisResults_pt_25_30.root,
  /home/wuct/ALICE/local/Results/pre/pre_k3050/AnRes/AnalysisResults_pt_30_35.root,
  /home/wuct/ALICE/local/Results/pre/pre_k3050/AnRes/AnalysisResults_pt_35_40.root,
  /home/wuct/ALICE/local/Results/pre/pre_k3050/AnRes/AnalysisResults_pt_40_50.root,
  /home/wuct/ALICE/local/Results/pre/pre_k3050/AnRes/AnalysisResults_pt_50_60.root,
  /home/wuct/ALICE/local/Results/pre/pre_k3050/AnRes/AnalysisResults_pt_60_70.root,
  /home/wuct/ALICE/local/Results/pre/pre_k3050/AnRes/AnalysisResults_pt_70_80.root,
  /home/wuct/ALICE/local/Results/pre/pre_k3050/AnRes/AnalysisResults_pt_80_100.root,
  /home/wuct/ALICE/local/Results/pre/pre_k3050/AnRes/AnalysisResults_pt_100_120.root,
  /home/wuct/ALICE/local/Results/pre/pre_k3050/AnRes/AnalysisResults_pt_120_160.root,
  /home/wuct/ALICE/local/Results/pre/pre_k3050/AnRes/AnalysisResults_pt_160_240.root
]
vn_method: 'sp'
nworkers: 20 # workers to parallelize projections, efficiency and fitting

harmonic: 2 # 2: v2, 3: v3, etc.

# pt bins
#        1    2     3     4     5     6     7     8     9     10    11    12    13    14    15
ptmins: [0.5, 1,    1.5,  2,    2.5,  3,    3.5,  4,    5,    6,    7,    8,    10,   12,   16]
ptmaxs: [1,   1.5,  2,    2.5,  3,    3.5,  4,    5,    6,    7,    8,    10,   12,   16,   24]

# inv_mass_bins (one for each pt bin)
inv_mass_bins: [
    [1.72,1.76,1.78,1.80,1.82,1.83,1.84,1.85,1.86,1.87,1.88,1.89,1.90,1.92,1.94,1.96,1.98,2.02], # pt 1
    [1.72,1.76,1.78,1.80,1.82,1.83,1.84,1.85,1.86,1.87,1.88,1.89,1.90,1.92,1.94,1.96,1.98,2.02], # pt 2
    [1.72,1.76,1.78,1.80,1.82,1.83,1.84,1.85,1.86,1.87,1.88,1.89,1.90,1.92,1.94,1.96,1.98,2.02], # pt 3
    [1.72,1.74,1.76,1.78,1.80,1.81,1.82,1.83,1.84,1.85,1.86,1.87,1.88,1.89,1.90,1.92,1.94,1.96,1.98,2.00,2.02], # pt 4
    [1.72,1.74,1.76,1.78,1.80,1.81,1.82,1.83,1.84,1.85,1.86,1.87,1.88,1.89,1.90,1.92,1.94,1.96,1.98,2.00,2.02], # pt 5
    [1.72,1.74,1.76,1.78,1.80,1.81,1.82,1.83,1.84,1.85,1.86,1.87,1.88,1.89,1.90,1.92,1.94,1.96,1.98,2.00,2.02], # pt 6
    [1.72,1.74,1.76,1.78,1.80,1.81,1.82,1.83,1.84,1.85,1.86,1.87,1.88,1.89,1.90,1.92,1.94,1.96,1.98,2.00,2.02], # pt 7
    [1.72,1.76,1.78,1.80,1.82,1.83,1.84,1.85,1.86,1.87,1.88,1.90,1.92,1.94,1.96,1.98,2.00,2.04], # pt 8
    [1.72,1.76,1.78,1.80,1.82,1.83,1.84,1.85,1.86,1.87,1.88,1.90,1.92,1.94,1.96,1.98,2.00,2.04], # pt 9
    [1.72,1.76,1.78,1.80,1.82,1.83,1.84,1.85,1.86,1.87,1.88,1.90,1.92,1.94,1.96,1.98,2.04], # pt 10
    [1.72,1.76,1.78,1.80,1.82,1.83,1.84,1.85,1.86,1.87,1.88,1.90,1.92,1.94,1.96,1.98,2.04], # pt 11
    [1.68,1.72,1.76,1.78,1.80,1.82,1.83,1.84,1.85,1.86,1.87,1.88,1.90,1.92,1.94,1.96,1.98,2.02,2.06], # pt 12
    [1.68,1.72,1.76,1.78,1.80,1.82,1.83,1.84,1.85,1.86,1.87,1.88,1.90,1.92,1.94,1.96,1.98,2.02,2.06], # pt 13
    [1.68,1.72,1.76,1.78,1.80,1.82,1.83,1.84,1.85,1.86,1.87,1.88,1.90,1.92,1.94,1.96,1.98,2.02,2.06], # pt 14
    [1.66,1.70,1.74,1.78,1.80,1.82,1.83,1.84,1.85,1.86,1.87,1.88,1.89,1.90,1.92,1.94,1.96,2.0,2.04,2.08] # pt 15
]
use_inv_mass_bins: false # use binning in invariant mass distribution, neglects inv_mass_bins (default: false)

# ep/sp subevents
detA: 'FT0c'
detB: 'FV0a'
detC: 'TPCtot'

#________________________________________________________________________________________________________________________
# fit options
Dmeson: 'Dzero'
Sigma: [0.01417, 0.014911120480742321, 0.015741026647936425, 0.016850244609005603, 0.017824384048723513, 0.018757969006450506, 0.019881227754034152, 0.021915830719224733, 0.024188357771437106, 0.0262078785574595, 0.03058851371381165, 0.03241829362746358, 0.03682312426229685, 0.04105900610940811, 0.051]
FixSigma: 1
FixSigmaFromFile: ''
SigmaFile: ''
SigmaMultFactor: 1.
FixMean: 0
MeanFile: ''
#          1     2     3     4     5     6     7     8     9     10    11    12    13    14    15    16
MassMin: [ 1.72, 1.72, 1.72, 1.72, 1.72, 1.72, 1.72, 1.72, 1.72, 1.72, 1.72, 1.68, 1.68, 1.68, 1.66, 1.74] 
MassMax: [ 2.02, 2.02, 2.02, 2.02, 2.02, 2.02, 2.02, 2.04, 2.04, 2.04, 2.04, 2.06, 2.06, 2.06, 2.08, 2.00]
Rebin:   [ 2,    2,    2,    2,    2,    2,    2,    4,    4,    4,    5,    5,    6,    8,    8,   20]
InclSecPeak: [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]
SigmaSecPeak: []
SigmaFileSecPeak: ''
SigmaMultFactorSecPeak: 1.
FixSigmaToFirstPeak: 0
UseLikelihood: 1
#          1        2        3        4        5        6        7        8        9        10       11       12       13       14       15       16       17       18       19       20       21
BkgFunc: [ 'kExpo', 'kExpo', 'kExpo', 'kExpo', 'kExpo', 'kExpo', 'kExpo', 'kExpo', 'kExpo', 'kExpo', 'kExpo', 'kPol3', 'kPol3', 'kPol3', 'kPol3', 'kExpo', 'kExpo', 'kExpo', 'kExpo', 'kExpo', 'kExpo' ]
SgnFunc: [ 'kGaus', 'kGaus', 'kGaus', 'kGaus', 'kGaus', 'kGaus', 'kGaus', 'kGaus', 'kGaus', 'kGaus', 'kGaus', 'kGaus', 'kGaus', 'kGaus', 'kGaus', 'kGaus', 'kGaus', 'kGaus', 'kGaus', 'kGaus', 'kGaus' ]
BkgFuncVn: ['kLin', 'kLin', 'kLin', 'kLin', 'kLin', 'kLin', 'kLin', 'kLin', 'kLin', 'kLin', 'kLin', 'kLin', 'kLin', 'kLin', 'kLin', 'kLin', 'kLin', 'kLin', 'kLin', 'kLin', 'kLin' ]
ReflFunc: "2gaus"
FixSigmaRatio: 0 # used only if SgnFunc = k2GausSigmaRatioPar
SigmaRatioFile: ""
BoundMean: 0 # 0: Do not set limits on mean range, 1: the mean is set to be between MassMin[i] and MassMax[i]

#________________________________________________________________________________________________________________________
# bdt cut
apply_btd_cuts: false # apply bdt cuts
bkg_ml_cuts: [0.08, 0.08, 0.08, 0.08, 0.08, 0.08] # max probability for bkg, one for each pt bin
sig_ml_cuts: [0.6, 0.6, 0.6, 0.6, 0.6, 0.6]       # min probability for sig, one for each pt bin

# cut variation
cut_variation:
       corr_bdt_cut:
              #         1      2      3      4      5      6      7      8      9      10     11     12     13     14     15
              bkg_max: [0.002, 0.002, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.002, 0.002, 0.005, 0.005, 0.01,  0.03,  0.05]
              sig: # the max value is not contained in the range
                min:   [0.30,  0.20,  0.24,  0.16,  0.16,  0.16,  0.16,  0.15,  0.15,  0.08,  0.10,  0.08,  0.08,  0.06,  0.10]
                max:   [0.85,  0.96,  0.96,  0.96,  0.96,  0.96,  0.96,  0.96,  0.96,  0.96,  0.96,  0.96,  0.96,  0.96,  0.96]
                step:  [0.03,  0.03,  0.03,  0.03,  0.03,  0.03,  0.03,  0.03,  0.03,  0.04,  0.04,  0.04,  0.04,  0.04,  0.04]
       uncorr_bdt_cut:
            bkg_max: # max probability for bkg, one for each pt bin
                - [0.002, 0.003, 0.003, 0.001] # pt 1
                - [0.002, 0.002, 0.002, 0.002, 0.002] # pt 2
                - [0.002, 0.002, 0.002, 0.002, 0.002] # pt 3
                - [0.002, 0.002, 0.002, 0.002, 0.002] # pt 4
                - [0.001, 0.002, 0.002, 0.002, 0.002] # pt 5
                - [0.002, 0.002, 0.002, 0.002, 0.002] # pt 6
                - [0.002, 0.002, 0.002, 0.002, 0.002] # pt 7
                - [0.004, 0.004, 0.004, 0.004, 0.004] # pt 8
                - [0.004, 0.004, 0.004, 0.005, 0.005] # pt 9
                - [0.007, 0.007, 0.007, 0.007] # pt 10
                - [0.008, 0.008, 0.008, 0.008] # pt 11
                - [0.02, 0.02, 0.02, 0.02] # pt 12
                - [0.04, 0.04, 0.04, 0.04] # pt 13
                - [0.09, 0.08, 0.08, 0.08] # pt 14
                - [0.16, 0.16, 0.16, 0.16] # pt 15
            sig:
                - min: [0.00, 0.50, 0.65, 0.82] # min pt 1
                  max: [0.50, 0.65, 0.82, 1.00] # max pt 1
                - min: [0.00, 0.30, 0.39, 0.52, 0.82] # min pt 2
                  max: [0.30, 0.39, 0.52, 0.82, 1.00] # max pt 2
                - min: [0.00, 0.32, 0.42, 0.58, 0.90] # min pt 3
                  max: [0.32, 0.42, 0.58, 0.90, 1.00] # max pt 3
                - min: [0.00, 0.27, 0.35, 0.48, 0.82] # min pt 4
                  max: [0.27, 0.35, 0.48, 0.82, 1.00] # max pt 4
                - min: [0.00, 0.30, 0.40, 0.50, 0.92] # min pt 5
                  max: [0.30, 0.40, 0.50, 0.92, 1.00] # max pt 5
                - min: [0.00, 0.22, 0.30, 0.45, 0.88] # min pt 6
                  max: [0.22, 0.30, 0.45, 0.88, 1.00] # max pt 6
                - min: [0.00, 0.22, 0.30, 0.45, 0.88] # min pt 7
                  max: [0.22, 0.30, 0.45, 0.88, 1.00] # max pt 7
                - min: [0.00, 0.20, 0.32, 0.47, 0.92] # min pt 8
                  max: [0.20, 0.32, 0.47, 0.92, 1.00] # max pt 8
                - min: [0.00, 0.18, 0.26, 0.40, 0.88] # min pt 9
                  max: [0.18, 0.26, 0.40, 0.88, 1.00] # max pt 9
                - min: [0.00, 0.20, 0.40, 0.88] # min pt 10
                  max: [0.20, 0.40, 0.88, 1.00] # max pt 10
                - min: [0.00, 0.20, 0.36, 0.86] # min pt 11
                  max: [0.20, 0.36, 0.86, 1.00] # max pt 11
                - min: [0.00, 0.16, 0.26, 0.86] # min pt 12
                  max: [0.16, 0.26, 0.86, 1.00] # max pt 12
                - min: [0.00, 0.16, 0.26, 0.86] # min pt 13
                  max: [0.16, 0.26, 0.86, 1.00] # max pt 13
                - min: [0.00, 0.13, 0.24, 0.80] # min pt 14
                  max: [0.13, 0.24, 0.80, 1.00] # max pt 14
                - min: [0.00, 0.14, 0.26, 0.70] # min pt 15
                  max: [0.14, 0.26, 0.70, 1.00] # max pt 15

minimisation:
    correlated: true # true --> fully correlated, false --> fully uncorrelated
    combined: False
    # `output_dir` in run_cutvar.sh
    correlatedPath: 'path/to/correlated'
    skip_cuts: [    # index of the specific cuts to skip for each pt bin
                [18,19,20,21,22,23,24,25], # pt 1
                [26], # pt 2
                [24,25,26], # pt 3
                [], # pt 4
                [], # pt 5
                [], # pt 6
                [], # pt 7
                [], # pt 8
                [], # pt 9
                [22,23,24,25,26], # pt 10
                [22,23,24,25,26], # pt 11
                [22,23,24,25,26], # pt 12
                [21,22,23,24,25,26], # pt 13
                [21,22,23,24,25,26], # pt 14
                [21,22,23,24,25,26], # pt 15
    ]
    systematics: ['even', 'random', 'odd', 'minus3low', '1in3', '1in4', 'minus3high', 'minus3']

# efficiency
eff_filename: '/media/wuct/wulby/ALICE/AnRes/D0_flow/pass4/ML/Results/k3050/AnalysisResults_mc_pass4.root'

#________________________________________________________________________________________________________________________
# optional settings
### path of pre-processed AnalysisResults files 
skim_out_dir: '/Users/mcosti/Analysis/Datasets/3050/skim3040bkgstrict'

### components distribution of v2
DrawVnComps: false  # draw single terms of vn function

### D0
enableRef: true #reflection for D0. 
# if `enableRef` is set to `true`,  and `ReflFile` is empty, then `ReflFile` will be aotumatically filled.
# if `ReflFile` is filled, then it will use the filled one
reflFile: ''

### Dplus correlated bkg template
IncludeKDETempls: [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]  # boolean flag to include templates or not
FromGrid: false # compute templates from TemplsInputs, else take them from file with FromFile flag
# To add more templates, use [part1, ... ,partN]
TemplsFlags: [2]  # flag of flagMcDecayRec to query the dataframe from which the KDE is obtained
TemplsInputs: ['/Users/mcosti/Analysis/Datasets/Templates/AO2D_325626.root']  # input AODs for templates
TemplsTreeNames: ['O2hfcanddplite'] # name of tree in the AO2D file
# init weights for mass templates and vn of templates
InitWeights: [[500], [500], [500], [500], [500], [500], [500], [500], [500], [500], [500], [500], [500], [500], [500]]
MinWeights: [[0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0],]
MaxWeights: [[1000], [1000], [1000], [1000], [1000], [1000], [1000], [1000], [1000], [1000], [1000], [1000], [1000], [1000], [1000]]
FixVnTemplToSgn: [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
VnInitWeights: [[0.1], [0.1], [0.1], [0.1], [0.1], [0.1], [0.1], [0.1], [0.1], [0.1], [0.1], [0.1], [0.1], [0.1], [0.1]]
VnMinWeights: [[0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0]]
VnMaxWeights: [[0.2], [0.2], [0.2], [0.2], [0.2], [0.2], [0.2], [0.2], [0.2], [0.2], [0.2], [0.2], [0.2], [0.2], [0.2]]
# InitBkg: [[initval_par0_ptbin0, lowlim_par0_ptbin0, upplim_par0_ptbin0], [initval_par1_ptbin0, lowlim_par1_ptbin0, upplim_par1_ptbin0]],[empty if no initialization]]
InitBkg: [[],[],[],[],[],[],[],[],[],[],[],[],[]]

#_______________________________________________________________________________________________________________________
# used for computting pT weights
Bspecie: Ball # only surport for Ball and BsBmix, empty means no B pt weights

rebin: 1
smooth: 100

shapes: {
    D: {
        # fonll is mandatory
        fonll: /media/wuct/wulby/ALICE/AnRes/fonll_pythia_beautyFFee_charmhadrons_5dot5tev_y0dot5.root,
        tamu: {
              enabled: true,
              file: /home/wuct/ALICE/local/DmesonAnalysis/models/tamu/PromptD0_TAMU_RAA_5TeV_3050.txt
              }
        #TODO: data shape for Ds?
    },
    B: {
        # fonll is mandatory
        fonll: /media/wuct/wulby/ALICE/AnRes/fonll_pythia_beautyFFee_charmhadrons_5dot5tev_y0dot5.root,
        tamu: {
            enabled: true,
            file: {
                B: /home/wuct/ALICE/local/DmesonAnalysis/models/tamu/B_TAMU_RAA_5TeV_3050.txt,
                Bs: ''
                }
        }
    }
}
# a given path to the weights, used for finer centrality binning
ptWeights_path: ''