pp13TeVPrompt:
    Particle: "Lc"
    FixSigma: 0
    SigmaFile: ""
    SigmaMultFactor: 1. #float or MinusUnc, PlusUnc
    FixMean: 0
    MeanFile: ""
    PtMin: [2, 4, 6, 8]
    PtMax: [4, 6, 8, 12]
    MassMin: [2.11, 2.11, 2.11, 2.11]
    MassMax: [2.44, 2.44, 2.44, 2.44]
    Rebin: [4, 4, 4, 4]
    InclSecPeak: [0, 0, 0, 0] # Ds only
    SigmaSecPeak: [0, 0, 0, 0] # Ds only
    SigmaFileSecPeak: "" # Ds only
    SigmaMultFactorSecPeak: 0 # Ds only
    FixSigmaToFirstPeak: 0
    UseLikelihood: 0
    BkgFunc: ["kPol2", "kPol2", "kPol2", "kPol2"]
    SgnFunc: ["kGaus", "kGaus", "kGaus", "kGaus"]

pp13TeVFD:
    Particle: "Lc"
    FixSigma: 1
    SigmaFile: "~/DmesonAnalysis/rawYields/ry_nsigcospV0_PromptEn.root"
    SigmaMultFactor: 1. #float or MinusUnc, PlusUnc
    FixMean: 0
    MeanFile: ""
    PtMin: [2, 4, 6, 8]
    PtMax: [4, 6, 8, 12]
    MassMin: [2.11, 2.11, 2.11, 2.11]
    MassMax: [2.44, 2.44, 2.44, 2.44]
    Rebin: [5, 5, 5, 5]
    InclSecPeak: [0, 0, 0, 0] # Ds only
    SigmaSecPeak: [0, 0, 0, 0] # Ds only
    SigmaFileSecPeak: "" # Ds only
    SigmaMultFactorSecPeak: 0 # Ds only
    FixSigmaToFirstPeak: 0
    UseLikelihood: 0
    BkgFunc: ["kPol2", "kPol2", "kPol2", "kPol2"]
    SgnFunc: ["kGaus", "kGaus", "kGaus", "kGaus"]
