inputs:
    ptweightsfile: ptweights/pp/NonPromptDplusWeights_LHC20a7.root
    enableBweights: true # only for pp (FONLL only), since no RAA prediction available for B mesons
    shapes:
        pythia: # always enabled --> unweighted
            efffile: ../../../AnalysisNonPromptDpp2017/Dplus/outputs/systematics/genptshape/Efficiency_Dplus_pp5TeV_FD_central_noWeights.root
        fonll:
            enabled: true
            efffile: ../../../AnalysisNonPromptDpp2017/Dplus/outputs/systematics/genptshape/Efficiency_Dplus_pp5TeV_FD_central.root
        tamu:
            enabled: false
            efffile: outputs/genptshape/Eff_Ds_010_FONLL_times_TAMU.root
        phsd:
            enabled: false
            efffile: outputs/genptshape/Eff_Ds_010_FONLL_times_PHSD.root
        mc@shq:
            enabled: false
            efffile: outputs/genptshape/Eff_Ds_010_FONLL_times_Gossiaux.root
        catania:
            enabled: false
            efffile: outputs/genptshape/Eff_Ds_010_FONLL_times_Catania.root

outputfile:
    directory: ../../../AnalysisNonPromptDpp2017/Dplus/outputs/systematics/genptshape/
    suffix: FONLL_D_B_shapes
