meson:
    Dspecie: Ds
    Bspecie: null # optional, needed for non-prompt analyses mainly

inputMC:
    filename: ptweights/DsPbPb/GenPtShape_LHC20g2a.root
    suffixCF: _prompt_010_strongPIDpt8_Raa # only for CF outputs otherwise null

shapes:
    D:
        fonll: # fonll is mandatory
            file: ../../models/fonll/FONLL_D_pp5_y05_pt0-50_100MeVbins.txt
        tamu:
            enabled: true
            file: ../../models/tamu/PromptDs_TAMU_RAA_5TeV_010.txt
        phsd:
            enabled: true
            file: ../../models/phsd/Ds_PHSD_RAA_5TeV_010.txt
        mc@shq:
            enabled: true
            file: ../../models/mcatshq/D_Gossiaux_RAA_5TeV_010.txt
        catania:
            enabled: true
            file: ../../models/catania/Ds_Catania_RAA_5TeV_010.dat
        lido:
            enabled: true
            file: ../../models/lido/D-meson-Raa-010.dat
        lgr:
            enabled: true
            file: ../../models/lgr/RAA_Prompt_Ds_0-10__ColRad_FragCoal.dat
    B:
        fonll: # fonll is mandatory
            file: ../../models/fonll/FONLL_B_pp5_y05_pt0-150_100MeVbins.txt
        tamu:
            enabled: false
            file:
                B: ''
                Bs: ''
        lido:
            enabled: false
            file: ''

options:
    rebin: 1
    smooth: 100

outputfile: ptweights/DsPbPb/PtWeigths_LHC20g2a.root
