meson:
    Dspecie: Ds
    Bspecie: null # optional, needed for non-prompt analyses mainly

inputMC:
    filename: /home/fcatalan/cernbox/Analyses/PbPb2018/Ds_wML/final/raa/pass3/GenPtShape_LHC20g2b.root
    suffixCF: _prompt_3050_strongPIDpt8_Raa # only for CF outputs otherwise null

shapes:
    D:
        fonll: # fonll is mandatory
            file: ../../models/fonll/FONLL_D_pp5_y05_pt0-50_100MeVbins.txt
        tamu:
            enabled: true
            file: ../../models/tamu/PromptDs_TAMU_RAA_5TeV_3050.txt
        phsd:
            enabled: true
            file: ../../models/phsd/Ds_PHSD_RAA_5TeV_3050.txt
        mc@shq:
            enabled: true
            file: ../../models/mcatshq/D_Gossiaux_RAA_5TeV_3050.txt
        catania:
            enabled: true
            file: ../../models/catania/Ds_Catania_RAA_5TeV_3050.dat
        lido:
            enabled: true
            file: ../../models/lido/D-meson-Raa-3050.dat
        lgr:
            enabled: true
            file: ../../models/lgr/RAA_Prompt_Ds_30-50__ColRad_FragCoal.dat
        datashape:
            enabled: true
            file: ../../../PhDThesis/chapter7/data/DsYield_method2_fd1_br1_Ds_3050_040521.root
            hSpectraName: 'hAAC'
            systErrName: 'AliHFSystErrAA'
            parConfig: 
                'alpha': [2., -10., 10.] #[init value, min. limit, max. limit]
                'beta': [0.6, -2, 2.]
                'gamma': [3., -10., 10.]
            controlFile: /home/fcatalan/cernbox/Analyses/PbPb2018/Ds_wML/final/check_ptWeights/DsYield_PbPb3050_Fitted.root
    B:
        fonll: # fonll is mandatory
            file: ../../models/fonll/FONLL_B_pp5_y05_pt0-150_100MeVbins.txt
        tamu:
            enabled: false
            file:
                B: ''
                Bs: ''
        lido:
            enabled: false
            file: ''

options:
    rebin: 1
    smooth: 100

outputfile: ptweights/DsPbPb/PtWeigths_LHC20g2b.root
