inputs:
    rho00: 
        files: [
          /home/skundu/Dstar_server/New/final_output/CHARM_MB_HELICITY.root,
          /home/skundu/Dstar_server/New/final_output/CHARM_HM_HELICITY.root,
          /home/skundu/Dstar_server/New/final_output/BEAUTY_MB_HELICITY.root,
          /home/skundu/Dstar_server/New/final_output/BEAUTY_HM_HELICITY.root
        ]
        histoname: Default_funcint
    fractions:
        files: [
          /home/fgrosa/Dstar_polarization/outputs/fraction/MB/DstarFraction_pp13TeV_MB_prompt_final.root,
          /home/fgrosa/Dstar_polarization/outputs/fraction/HM/DstarFraction_pp13TeV_HM_prompt_final.root,
          /home/fgrosa/Dstar_polarization/outputs/fraction/MB/DstarFraction_pp13TeV_MB_FD_final.root,
          /home/fgrosa/Dstar_polarization/outputs/fraction/HM/DstarFraction_pp13TeV_HM_FD_final.root,
        ]
        histonames: 
            prompt: hPromptFrac
            nonprompt: hFDFrac
    ptbins:
        min: [5., 7., 10.]
        max: [7., 10., 20.]

output:
    file: /home/fgrosa/Dstar_polarization/outputs/results/Rho00_corr_HELICITY_ResolutionFIX # w/o extension
