meson: Dplus

reffilenames:
    data: ../../../AnalysisNonPromptDpp2017/Dplus/outputs/rawyields/RawYieldsDplus_pp5TeV_FD_central.root
    MC: ../../../AnalysisNonPromptDpp2017/Dplus/outputs/rawyields/RawYieldsDplus_pp5TeV_prompt_central.root

outfilename: ../../../AnalysisNonPromptDpp2017/Dplus/outputs/systematics/rawyields/RawYieldSyst_Dplus_pp5TeV_FD_central2.root

multitrial:
    mins: [ 1.66, 1.68, 1.70, 1.72, 1.74, 1.76 ] # lower fit limit
    maxs: [ 1.95, 1.96, 1.97, 1.98, 1.99, 2.00 ] # upper fit limit
    rebins: [ 4, 5, 6, 7, 8, 9, 10 ] # mass rebin values
    sgnfuncs: [ kGaus ] # signal functions of AliHFInvMassFitter
    bkgfuncs: [ kExpo, kLin, kPol2 ] # bkg functions of AliHFInvMassFitter
    sigma: [ kFixed, kFixedMinusUnc, kFixedPlusUnc ] 
    # other possibilities: 
    # kFree, kFixedMinus10Perc, kFixedPlus10Perc, kFixedMinus15Perc, kFixedPlus15Perc, kFixedMinus20Perc, kFixedPlus20Perc
    # those with variations (Plus/Minus) are exclusive (i.e. it is not possible to run with 10% and 15% variation at the same time)
    mean: [ kFree ] # other possibilities: kFixed
    bincounting:
        nsigma: [ 3, 5 ] # multi-trial will be repeated for each nsigma value

quality:
    chisquare:
        min: 0.
        max: 2.
