particle: Lc

reffilenames:
    data: ~/Lc_plots/rawYields/completeplus/RawYieldsLc_completeplus_FDEn.root
    MC: ~/Lc_plots/rawYields/completeplus/RawYieldsLc_completeplus_PromptEn.root
    # MC: null

output:
    filename: ~/Lc_plots/systematics/rawyields/completeplus/syst_Lc_completeplus_FDEn.root
    drawpurity: 0 # 0: False, 1: True

multitrial:
    ptbins: null #list of pt bins, set null if you want to keep them all
    mins: [2.11, 2.12, 2.13, 2.14, 2.15] # lower fit limit
    maxs: [2.39, 2.40, 2.41, 2.43, 2.44] # upper fit limit
    rebins: [3, 4, 5, 6, 7, 8] # mass rebin values
    sgnfuncs: [kGaus] # signal functions of AliHFInvMassFitter
    bkgfuncs: [kPol2, kPol3] # bkg functions of AliHFInvMassFitter
    sigma: [kFixed, kFixedMinusUnc, kFixedPlusUnc]
    # all possibilities:
    # kFree, kFixed, kFixedMinus10Perc, kFixedPlus10Perc, kFixedMinus15Perc, kFixedPlus15Perc, kFixedMinus20Perc, kFixedPlus20Perc, kFixedMinusUnc, kFixedPlusUnc
    # those with variations (Plus/Minus) are exclusive (i.e. it is not possible to run with 10% and 15% variation at the same time)
    mean: [kFree] # other possibilities: kFixed
    # all possibilities:
    # kFixed, kFree, kFixedMinusUnc, kFixedPlusUnc
    bincounting:
        nsigma: [3, 5] # multi-trial will be repeated for each nsigma value
    nsigma4purity: 3

quality:
    chisquare:
        min: 0.
        max: 2.5
