meson: Dplus

reffilenames:
    data: ../../../Analysispp2017DplusLowPt/outputs/rawyields/RawYields_Dplus_pp5TeV_central.root
    MC: ../../../Analysispp2017DplusLowPt/outputs/rawyields/RawYields_Dplus_pp5TeV_central.root

outfilename: ../../../Analysispp2017DplusLowPt/outputs/systematics/rawyields/RawYieldSyst_Dplus_pp5TeV_Prompt_central_pt24-36.root

multitrial:
    ptbins: [ 20 ] #list of pt bins, set null if you want to keep them all
    mins: [ 1.66, 1.67, 1.68, 1.69, 1.72, 1.73 ] # lower fit limit
    maxs: [ 2.00, 2.01, 2.02, 2.03, 2.04, 2.05 ] # upper fit limit
    rebins: [ 8, 9, 10, 11, 12, 14 ] # mass rebin values
    sgnfuncs: [ kGaus ] # signal functions of AliHFInvMassFitter
    #bkgfuncs: [ kPol2, kPol3, kPol4 ] # bkg functions of AliHFInvMassFitter
    bkgfuncs: [ kExpo, kLin ] # bkg functions of AliHFInvMassFitter
    sigma: [ kFree, kFixedMinusUnc, kFixedPlusUnc ] 
    # all possibilities: 
    # kFree, kFixed, kFixedMinus10Perc, kFixedPlus10Perc, kFixedMinus15Perc, kFixedPlus15Perc, kFixedMinus20Perc, kFixedPlus20Perc, kFixedMinusUnc, kFixedPlusUnc
    # those with variations (Plus/Minus) are exclusive (i.e. it is not possible to run with 10% and 15% variation at the same time)
    mean: [ kFree ]
    # all possibilities: 
    # kFixed, kFree, kFixedMinusUnc, kFixedPlusUnc
    bincounting:
        nsigma: [ 3, 5 ] # multi-trial will be repeated for each nsigma value

quality:
    chisquare:
        min: 0.
        max: 2.
