particle: Dplus

reffilenames:
    data: ../../../Analysispp2017DplusLowPt/outputs/rawyields/RawYields_Dplus_pp5TeV_central.root
    MC: ../../../Analysispp2017DplusLowPt/outputs/rawyields/RawYields_Dplus_pp5TeV_central.root

output:
    filename: ../../../Analysispp2017DplusLowPt/outputs/systematics/rawyields/RawYieldSyst_Dplus_pp5TeV_Prompt_central_pt0-1.root
    drawpurity: 0 # 0: False, 1: True

multitrial:
    ptbins: [ 0 ] #list of pt bins, set null if you want to keep them all
    mins: [ 1.66, 1.68, 1.70, 1.72, 1.74, 1.76 ] # lower fit limit
    maxs: [ 1.96, 1.97, 1.98, 2.00, 2.01, 2.02 ] # upper fit limit
    rebins: [ 2, 3, 4, 5, 6, 7, 8 ] # mass rebin values
    sgnfuncs: [ kGaus ] # signal functions of AliHFInvMassFitter
    bkgfuncs: [ kPol2, kPol3, kPol4 ] # bkg functions of AliHFInvMassFitter
    sigma: [ kFree ] 
    # all possibilities: 
    # kFree, kFixed, kFixedMinus10Perc, kFixedPlus10Perc, kFixedMinus15Perc, kFixedPlus15Perc, kFixedMinus20Perc, kFixedPlus20Perc, kFixedMinusUnc, kFixedPlusUnc
    # those with variations (Plus/Minus) are exclusive (i.e. it is not possible to run with 10% and 15% variation at the same time)
    mean: [ kFree, kFixedMinusUnc, kFixedPlusUnc ]
    # all possibilities: 
    # kFixed, kFree, kFixedMinusUnc, kFixedPlusUnc
    bincounting:
        nsigma: [ 3, 5 ] # multi-trial will be repeated for each nsigma value
    nsigma4purity: 3

quality:
    chisquare:
        min: 0.
        max: 2.
