inKineFileName: BhadronsToDs_FONLLptShape_pp5TeV.root
outFileName: NonPromptDs_BhadronsFONLLptShape_FFppbar_Pythia8Decayer_pp5TeV.root
pdgCodeB: [ 511, 521, 531, 5122 ]
pdgCodeD: [ 431 ]
partPlusAntiPart: true
FFbtoB: [0.34, 0.34, 0.101, 0.218] # B+, B0, Bs, Lb
BRD: [ 0.0227 ]
