inputs:
    dirname: null # leave null if not common for all input files
    filenames: [../../AnalysisNonPromptDpp2017/Dplus/outputs/crosssection/CrossSectionDplus_pp5TeV_FD_central.root, 
                ../../AnalysisNonPromptDpp2017/Dplus/outputs/systematics/fraction/narrower_left/CrossSection_FD_Fraction_narrower_left.root,
                ../../AnalysisNonPromptDpp2017/Dplus/outputs/systematics/fraction/narrower_right/CrossSection_FD_Fraction_narrower_right.root,
                ../../AnalysisNonPromptDpp2017/Dplus/outputs/systematics/fraction/narrower/CrossSection_FD_Fraction_narrower.root,
                ../../AnalysisNonPromptDpp2017/Dplus/outputs/systematics/fraction/wider_left/CrossSection_FD_Fraction_wider_left.root,
                ../../AnalysisNonPromptDpp2017/Dplus/outputs/systematics/fraction/wider_right/CrossSection_FD_Fraction_wider_right.root,
                ../../AnalysisNonPromptDpp2017/Dplus/outputs/systematics/fraction/wider/CrossSection_FD_Fraction_wider.root,
                ../../AnalysisNonPromptDpp2017/Dplus/outputs/systematics/fraction/step1/CrossSection_FD_Fraction_step1.root,
                ../../AnalysisNonPromptDpp2017/Dplus/outputs/systematics/fraction/step2/CrossSection_FD_Fraction_step2.root]
    objectnames: [hFDFrac, hFDFrac, hFDFrac, hFDFrac, hFDFrac, hFDFrac, hFDFrac, hFDFrac, hFDFrac] # can be either histograms of graphs or a mix of them; they will be drawn in the current order

output: 
    filename: ../../AnalysisNonPromptDpp2017/Dplus/outputs/systematics/fraction/FDFrac_SystemVariation # with path and w/o extension
    extensions: [pdf, root] # possibilities: pdf, eps, png, root

options:
    ROOTobject: [TH1, TH1, TH1, TH1, TH1, TH1, TH1, TH1, TH1] # TH1 or TGraph: no need to specify TH1F, TH1D or TGraphErrors, TGraphAsymmErrors
    scale: [1., 1., 1., 1., 1., 1., 1., 1., 1.]
    lambdaParams: [1., 1., 1., 1., 1., 1., 1., 1., 1.] # counts -> (counts - 1) * lambda + 1
    normalize: [false, false, false, false, false, false, false, false, false] # divide histogram by its area
    colors: [kBlack, kRed+1, kAzure+4, kGreen+2, kOrange+7, kMagenta+1, kBlue, kCyan+3, kSpring-5]
    markers: [kFullCircle, kFullCircle, kFullCircle, kFullCircle, kFullCircle, kFullCircle, kFullCircle, kFullCircle, kFullCircle]
    markersize: 2.5
    linewidth: 5
    fillstyle: [1,1,1,1]
    fillalpha: [1,1,1,1]
    drawopt: [e, e, e, e, e, e, e, e, e]
    
    ratio: 
        enable: true
        uncertainties:
            enable: false
            corr: false
        displayRMS: true

    errcomp: # comparison of uncertainties
        enable: true
        relative: true

    legend:
        avoid: false #set true to avoid the legend in the final plot
        xlimits: [0.2, 0.6]
        ylimits: [0.6, 0.9]
        header: null
        titles: [central, narrow left, narrow right, narrow left and right, wide left, wide right, wide left and right, alt step 1, alt step 2]
        options: [lp, lp, lp, lp, lp, lp, lp, lp, lp]
        textsize: 0.045
        ncolumns: 2

    canvas:
        width: 1920
        heigth: 1080
        xaxistitle: '#it{p}_{T} (GeV/#it{c})'
        yaxistitle: '#it{f}_{non-prompt}'
        xlimits: [2., 16.]
        ylimits: [0., 2.]
        ylimitsratio: [0., 2.]
        ylimitserr: [0., 0.35]
        logy: true
        logx: false
        ratio:
            logy: false
            logx: false
        errcomp:
            logy: false
            logx: false  
