inputs:
    dirname: null # leave null if not common for all input files
    filenames: [/home/fchinu/Ds_pp_13TeV/output_analysis/HFPTSpectrumDs_pp13TeV.root,
                /home/fchinu/Ds_pp_13TeV/output_analysis/stefano/HFPtSpectrum_Ds_pp13TeV_wMultiClass_Ds_pp13TeV_PromptEn_22112021.root,
                /home/fchinu/Ds_pp_13TeV/output_analysis/stefano/HFPtSpectrum_CentralConsPID.root,
                /home/fchinu/Ds_pp_13TeV/output_analysis/stefano/HFPtSpectrum_CentralStrongPID.root
                ]

    objectnames: [histoSigmaCorr,histoSigmaCorr,histoSigmaCorr,histoSigmaCorr] # can be either histograms of graphs or a mix of them; they will be drawn in the current order

output: 
    filename: /home/fchinu/Ds_pp_13TeV/output_analysis/sigmacomparison # with path and w/o extension
    extensions: [png, root] # possibilities: pdf, eps, png, root

options:
    ROOTobject: [TH1, TH1, TH1, TH1, TH1, TH1, TH1, TH1] # TH1 or TGraph: no need to specify TH1F, TH1D or TGraphErrors, TGraphAsymmErrors
    scale: [4.16e-5, 4.16e-5, 4.16e-5, 4.16e-5]
    lambdaParams: [1., 1., 1., 1., 1., 1., 1., 1., 1.] # counts -> (counts - 1) * lambda + 1
    normalize: [false, false, false, false, false, false, false, false, false] # divide histogram by its area
    colors: [kAzure+3,  kBlack,  kGreen-2, kOrange-3]
    markers: [kFullCircle, kFullDiamond, kFullSquare,  kFullCross]
    markersize: 2.5
    linewidth: 5
    fillstyle: [1,1,1,1]
    fillalpha: [1,1,1,1]
    drawopt: [e, e, e, e, e, e, e, e, e]
    
    ratio: 
        enable: true
        uncertainties:
            enable: false
            corr: false
        displayRMS: true

    errcomp: # comparison of uncertainties
        enable: false
        relative: false

    legend:
        avoid: false #set true to avoid the legend in the final plot
        xlimits: [0.5, 0.9]
        ylimits: [0.6, 0.9]
        header: null
        titles: ['Binary', 'Multiclass', 'Std (Cons. PID)','Std (Strong PID)']
        options: [lp, lp, lp, lp, lp, lp, lp, lp, lp]
        textsize: 0.045
        ncolumns: 1

    canvas:
        width: 1920
        heigth: 1080
        xaxistitle: '#it{p}_{T} (GeV/#it{c})'
        yaxistitle: '#frac{d#sigma}{dp_{T}} (#mub GeV^{-1}c)'
        xlimits: [1., 36.]
        ylimits: [0.001, 1.e+3]
        ylimitsratio: [0.2, 1.4]
        ylimitserr: [0., 0.35]
        logy: true
        logx: false
        ratio:
            logy: false
            logx: false
        errcomp:
            logy: false
            logx: false  
