channel: D0 # options [Ds, Dplus, LctopKpi, LctopK0s, LctopiL]

infile:
    isMC: 0
    filename: /Users/zbiao/noprompt_study/DmesonAnalysis/filterdata/data_mc/data.root
    dirname: PWGHF_D2H_TreeD0toKpiLoose
    treename: treeMLD

outfile:
    dirpath: '../../AnalysisNonPromptD013TeVpp/D0/data_tree'
    suffix: _D0pp13TeV_data
    treename: treeMLD
    
skimming:
    pt:
        min: 0
        max: 30
    preselections: nsigComb_Pi_0 > 0 and nsigComb_Pi_0 < 5 and nsigComb_Pi_1 > 0 and nsigComb_Pi_1 < 5 and nsigComb_K_0 > 0 and nsigComb_K_0 < 5 and nsigComb_K_1 > 0 and nsigComb_K_1 < 5 and  inv_mass < 2.1 and inv_mass > 1.65 #null if you don't want to apply preselections
    colstokeep: [inv_mass, pt_cand, d_len_xy, norm_dl_xy, cos_p_xy, imp_par_xy, max_norm_d0d0exp, cos_t_star,imp_par_prod, nsigComb_Pi_0, nsigComb_K_0, nsigComb_Pi_1, nsigComb_K_1] #empty list if you want to keep everything

singletrackvars:
    addAODfiltervars: 0 # it adds min pt and min d0 of daughters with pt < 2

missingvalues: # values in dataframe to be replaced with NaN (only possible with python script)
    enable: 0
    toreplace:
        nsigTOF_Pi_0: -999.
        nsigTOF_K_0: -999.
        nsigTOF_Pi_1: -999.
        nsigTOF_K_1: -999.
       
