infile:
    isMC: 1
    filename: [~/cernbox/ALICE_WORK/Files/Trains/Run2/LHC20a8/AnalysisResults_Dplus_Ds_QA.root]
    dirname: PWG3_D2H_InvMassDplus
    treename: treeMLDplus

outfile:
    dirpath: '../../AnalysisNonPromptDpp2017/Dplus/MC/LHC20a8'
    suffix: _Dpluspp5TeV_LHC20a8
    treename: treeMLDplus
    
skimming:
    pt:
        min: 1
        max: 50
    preselections: nsigComb_Pi_0 > 0 and nsigComb_Pi_1 > 0 and nsigComb_Pi_2 > 0 and nsigComb_K_0 > 0 and nsigComb_K_1 > 0 and nsigComb_K_2 > 0 #null if you don't want to apply preselections
    colstokeep: [inv_mass, pt_cand, d_len, d_len_xy, norm_dl_xy, cos_p, cos_p_xy, imp_par_xy, sig_vert, max_norm_d0d0exp, nsigComb_Pi_0, nsigComb_K_0, nsigComb_Pi_1, nsigComb_K_1, nsigComb_Pi_2, nsigComb_K_2, pt_B] #empty list if you want to keep everything

singletrackvars:
    addAODfiltervars: 0 # it adds min pt and min d0 of daughters with pt < 2

missingvalues: # values in dataframe to be replaced with NaN (only possible with python script)
    enable: 0
    toreplace:
        nsigTOF_Pi_0: -999.
        nsigTOF_K_0: -999.
        nsigTOF_Pi_1: -999.
        nsigTOF_K_1: -999.
        nsigTOF_Pi_2: -999.
        nsigTOF_K_2: -999.