channel: LctopK0s # options [Ds, Dplus, LctopKpi, LctopK0s, LctopiL]

infile:
    isMC: 1
    filename:
        [
            /data/shared/NonPromptLc/MC/LHC20f4c_2016/AnalysisResults_allPIDvars.root,
            /data/shared/NonPromptLc/MC/LHC20f4b_2017/AnalysisResults_allPIDvars.root,
            /data/shared/NonPromptLc/MC/LHC20f4a_2018/AnalysisResults_allPIDvars.root,
        ]
    dirname: PWGHF_D2H_NonPromptLctopK0sLoose
    treename: treeMLLc

outfile:
    dirpath: /data/dbattistini/filtered/
    suffix: _filter_eff
    treename: treeMLLc

skimming:
    pt:
        min: [2, 4, 6, 8]
        max: [4, 6, 8, 12]

    preselections: inv_mass > 2.1 and inv_mass < 2.45 and
        delta_mass_K0s > 0 and delta_mass_K0s < 0.5 and
        d_len < 25 and
        d_len_xy < 25 and
        imp_par_xy > -5 and imp_par_xy < 5 and
        dca < 6 and
        KF_chi2_topo > 0 and KF_chi2_topo < 1000 and
        nsigTPC_Pi_0 < 150 and
        nsigTPC_Pr_0 < 6 and
        nsigTOF_Pi_0 < 210 and
        nsigComb_Pi_0 <  150 and
        nsigComb_Pr_0 < 30 and
        nsigTPC_Pi_1 < 10 and
        nsigTPC_Pr_1 < 10 and
        nsigTOF_Pi_1 < 80 and
        nsigComb_Pi_1 < 50 and
        nsigComb_Pr_1 < 50 and
        nsigTPC_Pi_2 < 10 and
        nsigTPC_Pr_2 < 10 and
        nsigTOF_Pi_2 < 100 and
        nsigComb_Pi_2 < 50 and
        cos_p_V0 > 0.95

    colstokeep: [
            inv_mass,
            pt_cand,
            d_len,
            d_len_xy,
            norm_dl_xy,
            cos_p,
            cos_p_xy,
            imp_par_xy,
            dca,
            nsigComb_Pi_0,
            nsigComb_Pr_0,
            signd0,
            delta_mass_K0s,
            dca_V0,
            imp_par_V0,
            d_len_V0,
            ctau_K0s,
            cos_p_V0,
            KF_chi2_topo,
            imp_par_prong0,
        ] #empty list if you want to keep everything

singletrackvars:
    addAODfiltervars: 0 # it adds min pt and min d0 of daughters with pt < 2

missingvalues: # values in dataframe to be replaced with NaN (only possible with python script)
    enable: 0
    tolerance:
        nsigTOF_Pi_0: -999.
        nsigTOF_Pr_0: -999.
