infile:
    isMC: 1
    filename: [~/cernbox/Analyses/pp5TeV/Ds_wML_mult/inputs/MC/LHC20a8/AnalysisResultsDsMC_LHC20a8_Tot.root]
    dirname: PWGHF_D2H_InvMassDs_Ds_Loose_kMB
    treename: treeMLDs

outfile:
    dirpath: ~/cernbox/Analyses/pp5TeV/Ds_wML_mult/inputs/MC/ml
    suffix: _Dspp5TeVNoOutlier_MLtraining
    treename: treeMLs
    
skimming:
    pt:
        min: 1
        max: 50
    preselections: nsigComb_Pi_0 > 0 and nsigComb_Pi_1 > 0 and nsigComb_Pi_2 > 0 and 
                   nsigComb_K_0 > 0 and nsigComb_K_1 > 0 and nsigComb_K_2 > 0 #null if you don't want to apply preselections
    colstokeep: [] #empty list if you want to keep everything

missingvalues: # values in dataframe to be replaced with NaN (only possible with python script)
    enable: 0
    toreplace:
        nsigTOF_Pi_0: -999.
        nsigTOF_K_0: -999.
        nsigTOF_Pi_1: -999.
        nsigTOF_K_1: -999.
        nsigTOF_Pi_2: -999.
        nsigTOF_K_2: -999.