channel: LctopK0s # options [Ds, Dplus, LctopKpi, LctopK0s, LctopiL]

infile:
    isMC: 1
    filename:
        [
            ~/DmesonAnalysis/AnalysisResults/13TeV/MC_D2H/AnalysisResults_LcpK0s_2016_LHC20f4c.root,
            ~/DmesonAnalysis/AnalysisResults/13TeV/MC_D2H/AnalysisResults_LcpK0s_2017_LHC20f4b.root,
            ~/DmesonAnalysis/AnalysisResults/13TeV/MC_D2H/AnalysisResults_LcpK0s_2018_LHC20f4a.root,
        ]
    dirname: PWGHF_D2H_NonPromptLctopK0sLoose
    treename: treeMLLc

outfile:
    dirpath: filtered/13TeV/
    suffix: _filter_eff
    treename: treeMLLc

skimming:
    pt:
        min: 6
        max: 50

    preselections: inv_mass > 2.1 and inv_mass < 2.45 and nsigTPC_Pr_0 > -3 and nsigTPC_Pr_0 < +3 and nsigTOF_Pr_0 > -40 and nsigTOF_Pr_0 < 10

    colstokeep: [
            inv_mass,
            pt_cand,
            d_len,
            d_len_xy,
            norm_dl_xy,
            cos_p,
            cos_p_xy,
            imp_par_xy,
            pt_prong0,
            nsigComb_Pi_0,
            nsigComb_Pr_0,
            signd0,
            delta_mass_K0s,
            d_len_V0,
            cos_p_V0,
            pt_V0,
            KF_chi2_topo,
            imp_par_prong0,
        ] #empty list if you want to keep everything

singletrackvars:
    addAODfiltervars: 0 # it adds min pt and min d0 of daughters with pt < 2

missingvalues: # values in dataframe to be replaced with NaN (only possible with python script)
    enable: 0
    tolerance:
        nsigTOF_Pi_0: -999.
        nsigTOF_Pr_0: -999.
