infiles:
    signal:
        prompt:
            filename: ~/DsPbPb_paper/training/final_010/pt2_4/Prompt_D2H_pT_2_4_ModelApplied.parquet.gzip
            dirname: null
            treename: null
        feeddown:
            filename: ~/DsPbPb_paper/training/final_010/pt2_4/FD_D2H_pT_2_4_ModelApplied.parquet.gzip
            dirname: null
            treename: null
    secpeak: # only for Ds
        prompt:
            filename: null
            dirname: null
            treename: null
        feeddown:
            filename: null
            dirname: null
            treename: null
        mean: 1.87 # fixed values of mean and sigma, used if histogram is not provided
        sigma: 0.008
    background:
        filename: ~/DsPbPb_paper/training/final_010/pt2_4/Data_pT_2_4_ModelApplied.parquet.gzip
        dirname: null
        treename: null
        nEvents: 98000 # number of events for bkg in dataframe (~98M divided by rejection factor: 1000)
        fractiontokeep: [0.9]
        isMC: false # if false bkg from SB
        fitFunc: expo # fit function for bkg from SB, e.g. pol1, pol2, expo
        nSigma: 4 # number of sigma from signal region, used to select SB
        impFit: true # true to use improved fit method similar to AliHFInvMassFitter
        corrfactor:
            filename: null # set null if no MC bkg correction is needed
            histoname: null

    preseleff: 
        filename: ~/DsPbPb_paper/eff/Eff_010_preFilt_noPtWeights.root
        prompthistoname: hEffPrompt
        feeddownhistoname: hEffFD
    acceptance: ~/DmesonAnalysis/accfiles/Acceptance_Toy_DsKKpi_yfidPtDep_etaDau09_ptDau100_FONLL5ptshape.root

predictions:
    crosssec:
        filename: ~/DmesonAnalysis/models/DmesonLcPredictions_502TeV_y05_FFee_BRpythia8_SepContr.root
        histonames: 
            prompt: hDsPhipitoKkpipred_max
            feeddown: hDsPhipitoKkpifromBpred_central_corr
    Raa:
        prompt: ~/DmesonAnalysis/models/tamu/PromptDs_TAMU_RAA_5TeV_010_ImprovedCoalescence.txt # can either be a fixed value or a text file
        feeddown: ~/DmesonAnalysis/models/tamu/NonPromptDs_TAMU_RAA_5TeV_010.txt # can either be a fixed value or a text file
        model: 'tamu'

nExpectedEvents: 98000000
sigmaMB: 1. #pb
Taa: 0.00000002326 #pb-1

expectedSignalFrom: 'prompt' # Choice between: 'prompt' or 'feeddown'

BkgCorrFactor:
    filename: null # set null if no MC bkg correction is needed
    histoname: null

ptmin: [2, 3]
ptmax: [3, 4]

dfparametercuts:
    name: null 
    min: null
    max: null
    enable: False  # enable cuts over df column query over each df and relative scan histos 

cutvars:
    ML_output:
        min: 0.98
        max: 0.9995
        step: 0.00005
        upperlowercut: Lower
