isMC: yes
filename: ../ML_DsAnalysis/QM_prel/inputs/MC/D2H_prod/3050/AnalysisResultsDs_MC_3050_LHC19c3b_Tot_wTRcut.root
dirname: PWG3_D2H_InvMassDs_MLappl3050_pt2_8
listname: coutputDs_MLappl3050_pt2_8
sparsenameAll: fnSparseReco_fromC
sparsenamePrompt: fnSparseReco_fromC
sparsenameFD: fnSparseReco_fromB
sparsenameGenPrompt: fnSparseAcc_fromC
sparsenameGenFD: fnSparseAcc_fromB
enableSecPeak: yes
sparsenamePromptSecPeak: fnSparseRecoDplus_fromC
sparsenameFDSecPeak: fnSparseRecoDplus_fromB
sparsenameGenPromptSecPeak: fnSparseAccDplus_fromC
sparsenameGenFDSecPeak: fnSparseAccDplus_fromB
normname: NormalizationCounter
histoevname: hNEvents