isMC: yes
filename: ../ML_DsAnalysis/QM_prel/inputs/MC/D2H_prod/010/010_run_071019_tightPre/AnalysisResultsDs_MC_010_LHC19c3a_Tot_wTRcut_tightPre.root
dirname: PWG3_D2H_InvMassDs_MLappl010_pt8_50
listname: coutputDs_MLappl010_pt8_50
sparsenameAll: null
sparsenamePrompt: fnSparseReco_fromC
sparsenameFD: fnSparseReco_fromB
sparsenameGenPrompt: fnSparseAcc_fromC
sparsenameGenFD: fnSparseAcc_fromB
enableSecPeak: yes
sparsenamePromptSecPeak: fnSparseRecoDplus_fromC
sparsenameFDSecPeak: fnSparseRecoDplus_fromB
sparsenameGenPromptSecPeak: fnSparseAccDplus_fromC
sparsenameGenFDSecPeak: fnSparseAccDplus_fromB
normname: NormalizationCounter
histoevname: hNEvents