isMC: no
isReducedVariables: yes
isWithBinfo: no # always no for data
filename: /home/fcatalan/Desktop/Analyses/PbPb2018/Ds_wML/final/raa/pass3/input/data/3050/MLapplied/AnalysisResults_Ds_3050_ML_LHC18qr_Tot_train1797.root
dirname: PWGHF_D2H_InvMassDs_MLappl3050
listname: coutputDs_MLappl3050
sparsenameAll: fnSparse
normname: NormalizationCounter
histoevname: hNEvents
enableRef: no #always no for data
enableSecPeak: no # always no for data
shiftForRedVariables: 11 # dependent on the sparse defined in the AliPhysics task
