filename: /home/fcatalan/Desktop/Analyses/PbPb2018/Ds_wML/final/v2/pass3/input/MLapplied/AnalysisResults_Ds_MLapplied271120_3050_v2_LHC18qr_Tot.root
dirname: [PWGHF_D2H_HFvn_Ds_v2_3050_MLapplVZEROC_EvShapeSP]
listname: [coutputvnDs_v2_3050_MLapplVZEROC_EvShapeSP]
sparsename: fHistMassPtPhiqnCentr
outfilename: /home/fcatalan/Desktop/Analyses/PbPb2018/Ds_wML/final/v2/pass3/input/MLapplied/AnalysisResults_Ds_MLapplied271120_3050_v2_LHC18qr_Tot_forV2.root
outdirname: PWGHF_D2H_HFvn_Ds_v2_3050_MLappl_VZEROC_EvShapeSP
outlistname: coutputvnDs_v2_3050_MLappl_VZEROC_EvShapeSP
