isMC: yes
isReducedVariables: no
isWithBinfo: yes
filename: /home/fcatalan/Desktop/Analyses/PbPb2018/Ds_wML/final/raa/pass3/input/MC/3050/D2H_MLapplied/AnalysisResultsDs_MC_3050_ML_LHC20g2b_2_Tot_train1823.root
dirname: PWGHF_D2H_InvMassDs_MLappl3050
listname: coutputDs_MLappl3050
sparsenameAll: null
sparsenamePrompt: fnSparseReco_fromC
sparsenameFD: fnSparseReco_fromB
sparsenameGenPrompt: fnSparseAcc_fromC
sparsenameGenFD: fnSparseAcc_fromB
enableRef: no #reflection for D0
enableSecPeak: yes
sparsenamePromptSecPeak: fnSparseRecoDplus_fromC
sparsenameFDSecPeak: fnSparseRecoDplus_fromB
sparsenameGenPromptSecPeak: fnSparseAccDplus_fromC
sparsenameGenFDSecPeak: fnSparseAccDplus_fromB
normname: NormalizationCounter
histoevname: hNEvents
shiftForRedVariables: 11 # dependent on the sparse defined in the AliPhysics task
