isMC: no
isReducedVariables: yes
isWithBinfo: no # always no for data
filename: /home/fcatalan/Desktop/Analyses/PbPb2018/Ds_wML/final/raa/pass3/input/data/010/MLapplied/AnalysisResults_Ds_010_ML_LHC18qr_Tot_train1798.root
dirname: PWGHF_D2H_InvMassDs_MLappl010
listname: coutputDs_MLappl010
sparsenameAll: fnSparse
normname: NormalizationCounter
histoevname: hNEvents
enableRef: no #always no for data
enableSecPeak: no # always no for data
shiftForRedVariables: 11 # dependent on the sparse defined in the AliPhysics task
