isMC: no
filename: ../ML_DsAnalysis/final/v2/input/AnalysisResults_Ds_ML_3050_v2_LHC18qr_Tot_wTRcut.root
dirname: PWG3_D2H_InvMassDs_MLappl3050_pt2_8
listname: coutputDs_MLappl3050_pt2_8
sparsenameAll: fnSparse
normname: NormalizationCounter
histoevname: hNEvents
enableSecPeak: no #always no for data
