output_dir: ./
outlabel: _limitedges_wchebpol2

fit_config:
  MB:
    pt_mins: [2.]
    pt_maxs: [24.]
    mass_mins: [0.55, 0.56, 0.58, 0.62]
    mass_maxs: [0.85, 0.83, 0.80, 0.78]
    signal_pdf: ["voigtian"]
    bkg_pdf: ["expopow", "chebpol1", "chebpol2"]
    gamma:  ["width", "width_upper", "width_lower"]
  HM:
    pt_mins: [2.]
    pt_maxs: [24.]
    mass_mins: [0.55, 0.56, 0.58, 0.62]
    mass_maxs: [0.85, 0.83, 0.80, 0.78]
    signal_pdf: ["voigtian"]
    bkg_pdf: ["expopow", "expo", "chebpol1", "chebpol2"]
    gamma:  ["width", "width_upper", "width_lower"]

quality_criteria: # to be satisfied to enter in systematic estimation
  chi2: 2
  significance: 3
