output_dir: ./
outlabel: _test_bash

fit_config:
  MB:
    pt_mins: [2.]
    pt_maxs: [24.]
    mass_mins: [0.5, 0.505, 0.51] # different from HM due to very unstable chi2
    mass_maxs: [0.6, 0.59, 0.58]
    signal_pdf: ["voigtian"]
    bkg_pdf: ["expopow", "powlaw", "expo", "chebpol2"]
    gamma:  ["width", "width_upper", "width_lower"]
  HM:
    pt_mins: [2.]
    pt_maxs: [24.]
    mass_mins: [0.5, 0.51]
    mass_maxs: [0.6, 0.58, 0.57, 0.56, 0.55]
    signal_pdf: ["voigtian"]
    bkg_pdf: ["expopow", "powlaw", "expo", "chebpol2"]
    gamma:  ["width", "width_upper", "width_lower"]

quality_criteria: # to be satisfied to enter in systematic estimation
  chi2: 2
  significance: 3