output_dir: ./
outlabel: _test_bash

fit_config:
  MB:
    pt_mins: [2.]
    pt_maxs: [24.]
    mass_mins: [0.50, 0.60]
    mass_maxs: [0.85, 0.80]
    signal_pdf: ["voigtian"]
    bkg_pdf: ["expopow", "expo"]
    gamma:  ["width", "width_upper", "width_lower"]
  HM:
    pt_mins: [2.]
    pt_maxs: [24.]
    mass_mins: [0.50, 0.60]
    mass_maxs: [0.85, 0.80]
    signal_pdf: ["voigtian"]
    bkg_pdf: ["expopow", "expo"]
    gamma:  ["width", "width_upper", "width_lower"]

quality_criteria: # to be satisfied to enter in systematic estimation
  chi2: 2
  significance: 3
