infiles:
    signal:
        prompt:
            filename:
                [
                    ~/Desktop/Ali50xl_copy/ml_training_out/BayesFinal_appl/pt1_2/Prompt_pT_1_2_ModelApplied.parquet.gzip,
                    ~/Desktop/Ali50xl_copy/ml_training_out/BayesFinal_appl/pt2_3/Prompt_pT_2_3_ModelApplied.parquet.gzip,
                    ~/Desktop/Ali50xl_copy/ml_training_out/BayesFinal_appl/pt3_5/Prompt_pT_3_5_ModelApplied.parquet.gzip,
                    ~/Desktop/Ali50xl_copy/ml_training_out/BayesFinal_appl/pt5_7/Prompt_pT_5_7_ModelApplied.parquet.gzip,
                    ~/Desktop/Ali50xl_copy/ml_training_out/BayesFinal_appl/pt7_12/Prompt_pT_7_12_ModelApplied.parquet.gzip,
                    ~/Desktop/Ali50xl_copy/ml_training_out/BayesFinal_appl/pt12_50/Prompt_pT_12_50_ModelApplied.parquet.gzip
                ]
            dirname: null
            treename: null
        feeddown:
            filename:
                [
                    ~/Desktop/Ali50xl_copy/ml_training_out/BayesFinal_appl/pt1_2/FD_pT_1_2_ModelApplied.parquet.gzip,
                    ~/Desktop/Ali50xl_copy/ml_training_out/BayesFinal_appl/pt2_3/FD_pT_2_3_ModelApplied.parquet.gzip,
                    ~/Desktop/Ali50xl_copy/ml_training_out/BayesFinal_appl/pt3_5/FD_pT_3_5_ModelApplied.parquet.gzip,
                    ~/Desktop/Ali50xl_copy/ml_training_out/BayesFinal_appl/pt5_7/FD_pT_5_7_ModelApplied.parquet.gzip,
                    ~/Desktop/Ali50xl_copy/ml_training_out/BayesFinal_appl/pt7_12/FD_pT_7_12_ModelApplied.parquet.gzip,
                    ~/Desktop/Ali50xl_copy/ml_training_out/BayesFinal_appl/pt12_50/FD_pT_12_50_ModelApplied.parquet.gzip
                ]
            dirname: null
            treename: null
    secpeak: # only for Ds
        prompt:
            filename: null
            dirname: null
            treename: null
        feeddown:
            filename: null
            dirname: null
            treename: null
        mean: 0 # fixed values of mean and sigma, used if histogram is not provided
        sigma: 0
    background:
        filename:
                  [
                    ~/Desktop/Ali50xl_copy/ml_training_out/BayesFinal_appl/pt1_2/Data_pT_1_2_ModelApplied.parquet.gzip,
                    ~/Desktop/Ali50xl_copy/ml_training_out/BayesFinal_appl/pt2_3/Data_pT_2_3_ModelApplied.parquet.gzip,
                    ~/Desktop/Ali50xl_copy/ml_training_out/BayesFinal_appl/pt3_5/Data_pT_3_5_ModelApplied.parquet.gzip,
                    ~/Desktop/Ali50xl_copy/ml_training_out/BayesFinal_appl/pt5_7/Data_pT_5_7_ModelApplied.parquet.gzip,
                    ~/Desktop/Ali50xl_copy/ml_training_out/BayesFinal_appl/pt7_12/Data_pT_7_12_ModelApplied.parquet.gzip,
                    ~/Desktop/Ali50xl_copy/ml_training_out/BayesFinal_appl/pt12_50/Data_pT_12_50_ModelApplied.parquet.gzip
                  ]
        dirname: null
        treename: null
        nEvents: 1683634000 # number of events for bkg in dataframe
        fractiontokeep: [0.1, 0.1] # 0.1, 0.2, 0.2, 0.2]
        # fractiontokeep: [0.1, 0.1, 0.2]
        isMC: false # if false bkg from SB
        fitFunc: expopow # fit function for bkg from SB, e.g. pol1, pol2, expo
        nSigma: 4 # number of sigma from signal region, used to select SB
        corrfactor:
            filename: null # set null if no MC bkg correction is needed
            histoname: null

    preseleff:
        filename: ~/Desktop/Ali50xl_copy/DmesonAnalysis/Dstar_effpresel.root
        prompthistoname: hEffPrompt
        feeddownhistoname: hEffFD
    acceptance: ~/Desktop/Ali50xl_copy/DmesonAnalysis/Acceptance_Toy_DStarD0pi_yfidPtDep_etaDau09_ptDau100_promptDstarFONLL13ptshape_FONLLy.root

ppRefFile: null

predictions:
    crosssec:
        filename: ~/Desktop/Ali50xl_copy/DmesonAnalysis/models/fonll/feeddown/DmesonLcPredictions_13TeV_y05_FFee_BRpythia8_SepContr_PDG2020.root
        histonames:
            prompt: hDstarD0pipred_central
            feeddown: hDstarD0pifromBpred_central_corr
    Raa:
        prompt: 1. # can either be a fixed value or a text file
        feeddown: 1. # can either be a fixed value or a text file
        model: null

nExpectedEvents: 1683634000
sigmaMB: 57.8e+9 #pb
Taa: 1.

expectedSignalFrom: "prompt" # Choice between: 'prompt' or 'feeddown'

ptmin: [1, 2] #, 3, 5, 7, 12]
ptmax: [2, 3] #, 5, 7, 12, 50]

minMass: 0.14
maxMass: 0.18

dfparametercuts:
    name: null
    min: null
    max: null
    enable: False # enable cuts over df column query over each df and relative scan histos

# cutvars: # prompt
#     ML_output_Bkg:
#         axisnum: null
#         min: 0.02
#         max: 0.50
#         step: 0.01
#         upperlowercut: Upper
#     ML_output_FD:
#         axisnum: null
#         min: 0.01
#         max: 0.9
#         step: 0.01
#         upperlowercut: Lower

cutvars: # fd
    ML_output_Bkg:
        axisnum: null
        min: [0.001,0.001] #,0.01,0.1,0.1,0.1]
        max:  [0.1,0.1] #,0.4,0.5,1, 1]
        step: [0.001,0.001] #,0.01,0.01,0.02,0.02]
        upperlowercut: Upper
    ML_output_FD:
        axisnum: null
        min: [0.1,0.1] #,0.1,0.1,0.1,0.1]
        max:  [0.98,0.98] #,0.98,0.98,0.98,0.98]
        step: [0.02,0.02] #,0.01,0.01,0.01,0.01]
        upperlowercut: Lower


specifier: basic