inputs:
    directory: ~/cernbox/ALICE_WORK/AnalysisNonPromptDpp2017/Dplus/outputs/systematics/cutvariation
    commonfilenames:
        rawyield: RawYieldsDplus
        efficiency: Efficiency_Dplus
        crosssection: CrossSectionDplus
    cutsets: [
              "_pp5TeV_FD_outFD_pos00",
              "_pp5TeV_FD_outbkg_neg01",
              "_pp5TeV_FD_outbkg_neg02",
              "_pp5TeV_FD_outbkg_neg03",
              "_pp5TeV_FD_outbkg_neg04",
              "_pp5TeV_FD_outbkg_neg05",
              "_pp5TeV_FD_outbkg_neg06",
              "_pp5TeV_FD_outbkg_neg07",
              "_pp5TeV_FD_outbkg_neg08",
              "_pp5TeV_FD_outbkg_neg09",
              "_pp5TeV_FD_outbkg_neg10",
              "_pp5TeV_FD_outbkg_pos00",
              "_pp5TeV_FD_outbkg_pos01",
              "_pp5TeV_FD_outbkg_pos02",
              "_pp5TeV_FD_outbkg_pos03",
              "_pp5TeV_FD_outbkg_pos04",
              "_pp5TeV_FD_outbkg_pos05",
              "_pp5TeV_FD_outbkg_pos06",
              "_pp5TeV_FD_outbkg_pos07",
              "_pp5TeV_FD_outbkg_pos08",
              "_pp5TeV_FD_outbkg_pos09",
              "_pp5TeV_FD_outbkg_pos10",
              "_pp5TeV_FD_outFD_neg01",
              "_pp5TeV_FD_outFD_neg02",
              "_pp5TeV_FD_outFD_neg03",
              "_pp5TeV_FD_outFD_neg04",
              "_pp5TeV_FD_outFD_neg05",
              "_pp5TeV_FD_outFD_neg06",
              "_pp5TeV_FD_outFD_neg07",
              "_pp5TeV_FD_outFD_neg08",
              "_pp5TeV_FD_outFD_neg09",
              "_pp5TeV_FD_outFD_neg10",
              "_pp5TeV_FD_outFD_pos01",
              "_pp5TeV_FD_outFD_pos02",
              "_pp5TeV_FD_outFD_pos03",
              "_pp5TeV_FD_outFD_pos04",
              "_pp5TeV_FD_outFD_pos05",
              "_pp5TeV_FD_outFD_pos06",
              "_pp5TeV_FD_outFD_pos07",
              "_pp5TeV_FD_outFD_pos08",
              "_pp5TeV_FD_outFD_pos09",
              "_pp5TeV_FD_outFD_pos10",
              "_pp5TeV_FD_outbkg_neg01_outFD_neg01",
              "_pp5TeV_FD_outbkg_neg01_outFD_neg02",
              "_pp5TeV_FD_outbkg_neg01_outFD_neg03",
              "_pp5TeV_FD_outbkg_neg01_outFD_pos00",
              "_pp5TeV_FD_outbkg_neg01_outFD_pos01",
              "_pp5TeV_FD_outbkg_neg01_outFD_pos02",
              "_pp5TeV_FD_outbkg_neg01_outFD_pos03",
              "_pp5TeV_FD_outbkg_neg02_outFD_neg01",
              "_pp5TeV_FD_outbkg_neg02_outFD_neg02",
              "_pp5TeV_FD_outbkg_neg02_outFD_neg03",
              "_pp5TeV_FD_outbkg_neg02_outFD_pos00",
              "_pp5TeV_FD_outbkg_neg02_outFD_pos01",
              "_pp5TeV_FD_outbkg_neg02_outFD_pos02",
              "_pp5TeV_FD_outbkg_neg02_outFD_pos03",
              "_pp5TeV_FD_outbkg_neg03_outFD_neg01",
              "_pp5TeV_FD_outbkg_neg03_outFD_neg02",
              "_pp5TeV_FD_outbkg_neg03_outFD_neg03",
              "_pp5TeV_FD_outbkg_neg03_outFD_pos00",
              "_pp5TeV_FD_outbkg_neg03_outFD_pos01",
              "_pp5TeV_FD_outbkg_neg03_outFD_pos02",
              "_pp5TeV_FD_outbkg_neg03_outFD_pos03",
              "_pp5TeV_FD_outbkg_pos00_outFD_neg01",
              "_pp5TeV_FD_outbkg_pos00_outFD_neg02",
              "_pp5TeV_FD_outbkg_pos00_outFD_neg03",
              "_pp5TeV_FD_outbkg_pos00_outFD_pos00",
              "_pp5TeV_FD_outbkg_pos00_outFD_pos01",
              "_pp5TeV_FD_outbkg_pos00_outFD_pos02",
              "_pp5TeV_FD_outbkg_pos00_outFD_pos03",
              "_pp5TeV_FD_outbkg_pos01_outFD_neg01",
              "_pp5TeV_FD_outbkg_pos01_outFD_neg02",
              "_pp5TeV_FD_outbkg_pos01_outFD_neg03",
              "_pp5TeV_FD_outbkg_pos01_outFD_pos00",
              "_pp5TeV_FD_outbkg_pos01_outFD_pos01",
              "_pp5TeV_FD_outbkg_pos01_outFD_pos02",
              "_pp5TeV_FD_outbkg_pos01_outFD_pos03",
              "_pp5TeV_FD_outbkg_pos02_outFD_neg01",
              "_pp5TeV_FD_outbkg_pos02_outFD_neg02",
              "_pp5TeV_FD_outbkg_pos02_outFD_neg03",
              "_pp5TeV_FD_outbkg_pos02_outFD_pos00",
              "_pp5TeV_FD_outbkg_pos02_outFD_pos01",
              "_pp5TeV_FD_outbkg_pos02_outFD_pos02",
              "_pp5TeV_FD_outbkg_pos02_outFD_pos03",
              "_pp5TeV_FD_outbkg_pos03_outFD_neg01",
              "_pp5TeV_FD_outbkg_pos03_outFD_neg02",
              "_pp5TeV_FD_outbkg_pos03_outFD_neg03",
              "_pp5TeV_FD_outbkg_pos03_outFD_pos00",
              "_pp5TeV_FD_outbkg_pos03_outFD_pos01",
              "_pp5TeV_FD_outbkg_pos03_outFD_pos02",
              "_pp5TeV_FD_outbkg_pos03_outFD_pos03",
              ] # the first one must be the default

outfilename: ~/cernbox/ALICE_WORK/AnalysisNonPromptDpp2017/Dplus/outputs/systematics/cutvariation/CutVariationSystematics_Dplus_pp5TeV_FD_1D_plus_2D.pdf

quality:
    maxchisquare: 2.
    minsignif: 3.
    minrelsignif: 0.5
    minreleff: 0.3
    maxreleff: 2.5
    fillthrreleff: 0.005

plots:
    plotrelativevar: 1 # 0 -> false, 1 -> true
    relassignedsyst: [ 0.10, 0.08, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05] # list of values to be plotted, null if you don't want to plot it
  