inputs:
    directory: ~/cernbox/Analyses/pp5TeV/Ds_wML_mult/outputs/100320/systematics/eff
    commonfilenames:
        rawyield: raw_yield/RawYieldsDs
        efficiency: eff/Efficiency_Ds
        crosssection: cross_sec/CrossSectionDs
    cutsets: ["_pp5TeV_FDen_outFD_pos00",
              "_pp5TeV_FDen_outBkg_neg01",
              "_pp5TeV_FDen_outBkg_neg02",
              "_pp5TeV_FDen_outBkg_neg03",
              "_pp5TeV_FDen_outBkg_neg04",
              "_pp5TeV_FDen_outBkg_neg05",
              "_pp5TeV_FDen_outBkg_neg06",
              "_pp5TeV_FDen_outBkg_neg07",
              "_pp5TeV_FDen_outBkg_neg08",
              "_pp5TeV_FDen_outBkg_neg09",
              "_pp5TeV_FDen_outBkg_neg10",
              "_pp5TeV_FDen_outBkg_pos01",
              "_pp5TeV_FDen_outBkg_pos02",
              "_pp5TeV_FDen_outBkg_pos03",
              "_pp5TeV_FDen_outBkg_pos04",
              "_pp5TeV_FDen_outBkg_pos05",
              "_pp5TeV_FDen_outBkg_pos06",
              "_pp5TeV_FDen_outBkg_pos07",
              "_pp5TeV_FDen_outBkg_pos08",
              "_pp5TeV_FDen_outBkg_pos09",
              "_pp5TeV_FDen_outBkg_pos10",
              "_pp5TeV_FDen_outFD_neg01",
              "_pp5TeV_FDen_outFD_neg02",
              "_pp5TeV_FDen_outFD_neg03",
              "_pp5TeV_FDen_outFD_neg04",
              "_pp5TeV_FDen_outFD_neg05",
              "_pp5TeV_FDen_outFD_neg06",
              "_pp5TeV_FDen_outFD_neg07",
              "_pp5TeV_FDen_outFD_neg08",
              "_pp5TeV_FDen_outFD_neg09",
              "_pp5TeV_FDen_outFD_neg10",
              "_pp5TeV_FDen_outFD_pos01",
              "_pp5TeV_FDen_outFD_pos02",
              "_pp5TeV_FDen_outFD_pos03",
              "_pp5TeV_FDen_outFD_pos04",
              "_pp5TeV_FDen_outFD_pos05",
              "_pp5TeV_FDen_outFD_pos06",
              "_pp5TeV_FDen_outFD_pos07",
              "_pp5TeV_FDen_outFD_pos08",
              "_pp5TeV_FDen_outFD_pos09",
              "_pp5TeV_FDen_outFD_pos10",
              "_pp5TeV_FDen_outFD_neg01_outBkg_neg01",
              "_pp5TeV_FDen_outFD_neg01_outBkg_neg02",
              "_pp5TeV_FDen_outFD_neg01_outBkg_neg03",
              "_pp5TeV_FDen_outFD_neg01_outBkg_pos00",
              "_pp5TeV_FDen_outFD_neg01_outBkg_pos01",
              "_pp5TeV_FDen_outFD_neg01_outBkg_pos02",
              "_pp5TeV_FDen_outFD_neg01_outBkg_pos03",
              "_pp5TeV_FDen_outFD_neg02_outBkg_neg01",
              "_pp5TeV_FDen_outFD_neg02_outBkg_neg02",
              "_pp5TeV_FDen_outFD_neg02_outBkg_neg03",
              "_pp5TeV_FDen_outFD_neg02_outBkg_pos00",
              "_pp5TeV_FDen_outFD_neg02_outBkg_pos01",
              "_pp5TeV_FDen_outFD_neg02_outBkg_pos02",
              "_pp5TeV_FDen_outFD_neg02_outBkg_pos03",
              "_pp5TeV_FDen_outFD_neg03_outBkg_neg01",
              "_pp5TeV_FDen_outFD_neg03_outBkg_neg02",
              "_pp5TeV_FDen_outFD_neg03_outBkg_neg03",
              "_pp5TeV_FDen_outFD_neg03_outBkg_pos00",
              "_pp5TeV_FDen_outFD_neg03_outBkg_pos01",
              "_pp5TeV_FDen_outFD_neg03_outBkg_pos02",
              "_pp5TeV_FDen_outFD_neg03_outBkg_pos03",
              "_pp5TeV_FDen_outFD_pos00_outBkg_neg01",
              "_pp5TeV_FDen_outFD_pos00_outBkg_neg02",
              "_pp5TeV_FDen_outFD_pos00_outBkg_neg03",
              "_pp5TeV_FDen_outFD_pos00_outBkg_pos01",
              "_pp5TeV_FDen_outFD_pos00_outBkg_pos02",
              "_pp5TeV_FDen_outFD_pos00_outBkg_pos03",
              "_pp5TeV_FDen_outFD_pos01_outBkg_neg01",
              "_pp5TeV_FDen_outFD_pos01_outBkg_neg02",
              "_pp5TeV_FDen_outFD_pos01_outBkg_neg03",
              "_pp5TeV_FDen_outFD_pos01_outBkg_pos00",
              "_pp5TeV_FDen_outFD_pos01_outBkg_pos01",
              "_pp5TeV_FDen_outFD_pos01_outBkg_pos02",
              "_pp5TeV_FDen_outFD_pos01_outBkg_pos03",
              "_pp5TeV_FDen_outFD_pos02_outBkg_neg01",
              "_pp5TeV_FDen_outFD_pos02_outBkg_neg02",
              "_pp5TeV_FDen_outFD_pos02_outBkg_neg03",
              "_pp5TeV_FDen_outFD_pos02_outBkg_pos00",
              "_pp5TeV_FDen_outFD_pos02_outBkg_pos01",
              "_pp5TeV_FDen_outFD_pos02_outBkg_pos02",
              "_pp5TeV_FDen_outFD_pos02_outBkg_pos03",
              "_pp5TeV_FDen_outFD_pos03_outBkg_neg01",
              "_pp5TeV_FDen_outFD_pos03_outBkg_neg02",
              "_pp5TeV_FDen_outFD_pos03_outBkg_neg03",
              "_pp5TeV_FDen_outFD_pos03_outBkg_pos00",
              "_pp5TeV_FDen_outFD_pos03_outBkg_pos01",
              "_pp5TeV_FDen_outFD_pos03_outBkg_pos02",
              "_pp5TeV_FDen_outFD_pos03_outBkg_pos03"
             ] # the first one must be the default

outfilename: ~/cernbox/Analyses/pp5TeV/Ds_wML_mult/outputs/100320/systematics/eff/CutVariationSystematics_Ds_pp5TeV_FD_1D_plus_2D.pdf

quality:
    maxchisquare: 2.
    minsignif: 3.
    minrelsignif: 0.5
    minreleff: 0.3
    maxreleff: 2.5
    fillthrreleff: 0.005

plots:
    plotrelativevar: 1 # 0 -> false, 1 -> true
    relassignedsyst: [0.07, 0.05, 0.05, 0.05] # list of values to be plotted, null if you don't want to plot it
  