rawyields:
    inputdir: rawYields/basic
    inputfiles: [
            RawYieldsLc_basic_outFD_neg01.root,
            # RawYieldsLc_basic_outFD_neg02.root,
            RawYieldsLc_basic_outFD_neg03.root,
            # RawYieldsLc_basic_outFD_neg04.root,
            RawYieldsLc_basic_outFD_neg05.root,
            # RawYieldsLc_basic_outFD_neg06.root,
            RawYieldsLc_basic_outFD_neg07.root,
            # RawYieldsLc_basic_outFD_neg08.root,
            RawYieldsLc_basic_outFD_neg09.root,
            # RawYieldsLc_basic_outFD_neg10.root,
            RawYieldsLc_basic_outFD_neg11.root,
            # RawYieldsLc_basic_outFD_neg12.root,
            RawYieldsLc_basic_outFD_neg13.root,
            # RawYieldsLc_basic_outFD_neg14.root,
            RawYieldsLc_basic_outFD_neg15.root,
            # RawYieldsLc_basic_outFD_neg16.root,
            RawYieldsLc_basic_outFD_neg17.root,
            # RawYieldsLc_basic_outFD_neg18.root,
            RawYieldsLc_basic_outFD_neg19.root,
            # RawYieldsLc_basic_outFD_neg20.root,
            RawYieldsLc_basic_outFD_pos00.root,
            # RawYieldsLc_basic_outFD_pos01.root,
            RawYieldsLc_basic_outFD_pos02.root,
            # RawYieldsLc_basic_outFD_pos03.root,
            RawYieldsLc_basic_outFD_pos04.root,
            # RawYieldsLc_basic_outFD_pos05.root,
        ]
    histoname: hRawYields

efficiencies:
    inputdir: efficiencies/basic
    inputfiles: [
            Eff_times_Acc_Lc_basic_outFD_neg01.root,
            # Eff_times_Acc_Lc_basic_outFD_neg02.root,
            Eff_times_Acc_Lc_basic_outFD_neg03.root,
            # Eff_times_Acc_Lc_basic_outFD_neg04.root,
            Eff_times_Acc_Lc_basic_outFD_neg05.root,
            # Eff_times_Acc_Lc_basic_outFD_neg06.root,
            Eff_times_Acc_Lc_basic_outFD_neg07.root,
            # Eff_times_Acc_Lc_basic_outFD_neg08.root,
            Eff_times_Acc_Lc_basic_outFD_neg09.root,
            # Eff_times_Acc_Lc_basic_outFD_neg10.root,
            Eff_times_Acc_Lc_basic_outFD_neg11.root,
            # Eff_times_Acc_Lc_basic_outFD_neg12.root,
            Eff_times_Acc_Lc_basic_outFD_neg13.root,
            # Eff_times_Acc_Lc_basic_outFD_neg14.root,
            Eff_times_Acc_Lc_basic_outFD_neg15.root,
            # Eff_times_Acc_Lc_basic_outFD_neg16.root,
            Eff_times_Acc_Lc_basic_outFD_neg17.root,
            # Eff_times_Acc_Lc_basic_outFD_neg18.root,
            Eff_times_Acc_Lc_basic_outFD_neg19.root,
            # Eff_times_Acc_Lc_basic_outFD_neg20.root,
            Eff_times_Acc_Lc_basic_outFD_pos00.root,
            # Eff_times_Acc_Lc_basic_outFD_pos01.root,
            Eff_times_Acc_Lc_basic_outFD_pos02.root,
            # Eff_times_Acc_Lc_basic_outFD_pos03.root,
            Eff_times_Acc_Lc_basic_outFD_pos04.root,
            # Eff_times_Acc_Lc_basic_outFD_pos05.root,
        ] #
    histonames:
        prompt: hAccEffPrompt
        feeddown: hAccEffFD

background: # needed only in case of smearing applied
    inputdir: rawYields/basic
    inputfiles: [
            RawYieldsLc_basic_outFD_neg01.root,
            # RawYieldsLc_basic_outFD_neg02.root,
            RawYieldsLc_basic_outFD_neg03.root,
            # RawYieldsLc_basic_outFD_neg04.root,
            RawYieldsLc_basic_outFD_neg05.root,
            # RawYieldsLc_basic_outFD_neg06.root,
            RawYieldsLc_basic_outFD_neg07.root,
            # RawYieldsLc_basic_outFD_neg08.root,
            RawYieldsLc_basic_outFD_neg09.root,
            # RawYieldsLc_basic_outFD_neg10.root,
            RawYieldsLc_basic_outFD_neg11.root,
            # RawYieldsLc_basic_outFD_neg12.root,
            RawYieldsLc_basic_outFD_neg13.root,
            # RawYieldsLc_basic_outFD_neg14.root,
            RawYieldsLc_basic_outFD_neg15.root,
            # RawYieldsLc_basic_outFD_neg16.root,
            RawYieldsLc_basic_outFD_neg17.root,
            # RawYieldsLc_basic_outFD_neg18.root,
            RawYieldsLc_basic_outFD_neg19.root,
            # RawYieldsLc_basic_outFD_neg20.root,
            RawYieldsLc_basic_outFD_pos00.root,
            # RawYieldsLc_basic_outFD_pos01.root,
            RawYieldsLc_basic_outFD_pos02.root,
            # RawYieldsLc_basic_outFD_pos03.root,
            RawYieldsLc_basic_outFD_pos04.root,
            # RawYieldsLc_basic_outFD_pos05.root,
        ]
    histoname: hRawYieldsBkg

minimisation:
    correlated: false # true --> fully correlated, false --> fully uncorrelated
    doRawYieldSmearing: false # whether to smear the yields with a poissonian error
    setseed: false # set the seed for Poissonian smearing
    applyEffVariation:
        enable: false
        relvariation: 0.05
        option: decreasing # available options: [upshift, downshift, decreasing, increasing]
        prompt: true
        feeddown: true

linearplot:
    enable: true #enable linear plots NpromptVsNFD
    uncbands: true #enable upper/lower linear plots limits
    outfileformat: ["pdf"] # linear plot saved in different output formats (e.g. png, pdf, etc.). Plots are already saved in the ouput TFile

theorydriven:
    enableFc: false
    enableNb: false
    predictions:
        crosssec:
            inputfile: models/DmesonLcPredictions_13TeV_y05_FFptDepLHCb_BRpythia8_PDG2020_PromptLcMod.root
            histonames:
                prompt: hLcK0sppred_max
                feeddown: hLcK0spfromBpred_max_corr
        Raa:
            prompt: 1.
            feeddown: 1.
            model: tamu # avaliable models: 'phsd', 'Catania', 'tamu', 'MCatsHQ'
    # below only needed for Nb
    sigmaMB: 57.8e+9
