BkgFuncVn: ["kPol2", "kLin", "kPol3"]
BkgFunc: ["kPol2", "kExpo", "kPol3"]
Rebin: [4, 6, 8]
inv_mass_bins: 
  min: 1.6
  max: 2.2
  steps: [0.01, 0.02, 0.04]
MassMin: [1.70, 1.72, 1.74]
MassMax: [2.2, 2.6, 2.1]
use_inv_mass_bins: [true, false]