### input files to be preprocessed
flow_files: [
       /media/wuct/wulby/ALICE/AnRes/D0_flow/pass4/ML/Results/324130/temp_merged_s3_0.root,
       /media/wuct/wulby/ALICE/AnRes/D0_flow/pass4/ML/Results/324130/temp_merged_s3_1.root,
       /media/wuct/wulby/ALICE/AnRes/D0_flow/pass4/ML/Results/324130/temp_merged_s3_2.root,
       /media/wuct/wulby/ALICE/AnRes/D0_flow/pass4/ML/Results/324130/temp_merged_s3_3.root,
       /media/wuct/wulby/ALICE/AnRes/D0_flow/pass4/ML/Results/324130/temp_merged_s3_4.root,
       /media/wuct/wulby/ALICE/AnRes/D0_flow/pass4/ML/Results/324130/temp_merged_s3_5.root,
       /media/wuct/wulby/ALICE/AnRes/D0_flow/pass4/ML/Results/324130/temp_merged_s3_6.root,
       /media/wuct/wulby/ALICE/AnRes/D0_flow/pass4/ML/Results/324130/temp_merged_s3_7.root
]

# pt ranges to be skimmed
ptmins: [0.5, 1,    1.5,  2,    2.5,  3,    3.5,  4,    5,    6,    7,    8,    10,   12,   16]
ptmaxs: [1,   1.5,  2,    2.5,  3,    3.5,  4,    5,    6,    7,    8,    10,   12,   16,   24]

# centrality class
centrality: 'k3050'
# output directory for preprocessed files
skim_out_dir: '/home/wuct/ALICE/local/Results/pre'
# bkg cuts, cut is applied then bkg axis is dropped. -1 means no cut
bkg_cuts: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, -1, -1, -1, -1, -1, -1, -1, -1]

# var names of axes to keep + rebin factors, -1 means no rebin
axestokeep: ['Mass', 'Pt', 'cent','sp', 'score_bkg', 'score_FD']
RebinSparse:
       Mass: -1
       sp: -1
       score_bkg: -1
       score_FD: -1
       Pt: 1
       cent: -1
