### input files to be preprocessed
flow_files: [
  /path/to/AnRes_0.root,
  /path/to/AnRes_1.root,
  /path/to/AnRes_2.root,
  /path/to/AnRes_3.root,
  /path/to/AnRes_4.root,
  /path/to/AnRes_5.root,
  /path/to/AnRes_6.root,
  /path/to/AnRes_7.root,
  /path/to/AnRes_8.root,
  /path/to/AnRes_9.root,
  /path/to/AnRes_10.root,
]

# pt ranges to be skimmed
ptmins: [0.0,0.5,1.0,1.5]
ptmaxs: [0.5,1.0,1.5,2.0]

# centrality class
centrality: 'k3040'
# output directory for preprocessed files
skim_out_dir: '/home/mdicosta/Datasets/3050/skim3040bkgstrict'
# bkg cuts, cut is applied then bkg axis is dropped
bkg_cuts: [0.002, 0.002, 0.002, 0.006]

# var names of axes to keep + rebin factors
axestokeep: ['Mass', 'sp', 'score_FD', 'Pt', 'cent']
RebinSparse:
       Mass: 2
       sp: 1
       score_FD: 10
       Pt: 1
       cent: 1
