### input files to be preprocessed
flow_files: [
  /Users/mcosti/Analysis/Datasets/3050/MERGED_0.root,
  /Users/mcosti/Analysis/Datasets/3050/MERGED_1.root,
  /Users/mcosti/Analysis/Datasets/3050/MERGED_2.root,
  /Users/mcosti/Analysis/Datasets/3050/MERGED_3.root,
  /Users/mcosti/Analysis/Datasets/3050/MERGED_4.root,
  /Users/mcosti/Analysis/Datasets/3050/MERGED_5.root,
  /Users/mcosti/Analysis/Datasets/3050/MERGED_6.root,
  /Users/mcosti/Analysis/Datasets/3050/MERGED_7.root,
  /Users/mcosti/Analysis/Datasets/3050/MERGED_8.root,
  /Users/mcosti/Analysis/Datasets/3050/MERGED_9.root,
  /Users/mcosti/Analysis/Datasets/3050/MERGED_10.root,
]

# pt ranges to be skimmed
ptmins: [0.0,0.5,1.0,1.5]
ptmaxs: [0.5,1.0,1.5,2.0]

# centrality class
centrality: 'k3040'
# output directory for preprocessed files
skim_out_dir: '/Users/mcosti/Analysis/Datasets/3050/skim3040bkgstrict'
# bkg cuts, cut is applied then bkg axis is dropped
bkg_cuts: [0.002, 0.002, 0.002, 0.006]

# var names of axes to keep + rebin factors
axestokeep: ['Mass', 'sp', 'score_FD', 'Pt', 'cent']
RebinSparse:
       Mass: 2
       sp: 1
       score_FD: 10
       Pt: 1
       cent: 1
